widget/app/public/index.css, widget/embedded/src/Widget.tsx, widget/embedded/src/components/AppRouter.tsx, widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/hooks/useNavigateBack.ts, widget/embedded/src/hooks/useSwapInput.ts, widget/embedded/src/pages/ConfirmSwapPage.tsx, widget/embedded/src/pages/HistoryPage.tsx, widget/embedded/src/pages/SelectSwapItemsPage.tsx, widget/embedded/src/utils/wallets.ts
(cherry picked from commit 67b3477e69209dec36e8027fbe23ea284a3ed5c0)
=> fix: fix widget navigation bugs

widget/embedded/src/components/AppRouter.tsx, widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/NoResult/NoResult.helpers.ts, widget/embedded/src/components/Quote/Quote.styles.ts, widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/components/Quote/Quote.types.ts, widget/embedded/src/components/Quote/QuoteSkeleton.tsx, widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.helpers.ts, widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.tsx, widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.types.ts, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.Cancel.tsx, widget/embedded/src/constants/errors.ts, widget/embedded/src/containers/QuoteInfo/QuoteInfo.styles.ts, widget/embedded/src/containers/QuoteInfo/QuoteInfo.tsx, widget/embedded/src/containers/QuoteInfo/QuoteInfo.types.ts, widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.helpers.ts, widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.ts, widget/embedded/src/hooks/useSwapInput.ts, widget/embedded/src/pages/ConfirmSwapPage.tsx, widget/embedded/src/pages/Home.tsx, widget/embedded/src/types/swap.ts, widget/embedded/src/utils/meta.ts, widget/embedded/src/utils/quote.ts, widget/embedded/src/utils/swap.ts, widget/ui/src/components/Alert/Alert.styles.ts, widget/ui/src/components/StepDetails/StepDetails.styles.ts, widget/ui/src/containers/SwapInput/SwapInput.tsx, widget/ui/src/containers/SwapInput/SwapInput.types.ts, widget/ui/src/containers/SwapInput/TokenSection.styles.ts
fixing the bugs in the ‘quote errors and warnings’ feature, as well as other minor bugs and improvements
I tested these changes with multiple routes and different slippages or swappers.
=> fix(widget-v2): fix quote info bugs

widget/embedded/src/containers/App/App.tsx, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.helpers.ts, widget/embedded/src/containers/WidgetInfo/WidgetInfo.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.types.ts
In the dapp we call meta as well & delaying in fetching meta caueses some issues. We decieded to get meta from useWidget hook.
there is a WIP pr in dapp side:
https://github.com/rango-exchange/app/pull/17
with linking it can be tested.
=> feat: export meta from useWidget

widget/embedded/src/components/Quote/Quote.styles.ts, widget/embedded/src/index.ts
=> fix: quote summary width

.github/workflows/crowdin.yml
=> fix: update github token

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/HeaderButtons/HeaderButtons.styles.ts, widget/embedded/src/components/Quote/QuoteSummary.tsx, widget/embedded/src/components/SwapsGroup/SwapsGroup.tsx, widget/embedded/src/pages/LiquiditySourcePage.tsx, widget/embedded/src/pages/SelectBlockchainPage.tsx, widget/embedded/src/pages/SelectSwapItemsPage.tsx, widget/embedded/src/utils/date.ts
Complete and check missing translations
Run Playground and change the language
=> fix: complete and check missing translations

translations/en.po, translations/es.po, translations/fr.po, translations/ja.po
New Crowdin pull request with translations
=> 🤖chore(translation): update translations

widget/embedded/src/components/Slippage/SlippageTooltipContent.tsx
For testing crowding changes, we need to update a text and then see if crowdin action works correctly.
=> chore: update message

widget/embedded/src/components/SwapDetails/SwapDetails.Placeholder.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.helpers.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.styles.ts, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/components/SwapDetailsAlerts/SwapDetailsAlerts.tsx, widget/embedded/src/components/SwapDetailsAlerts/SwapDetailsAlerts.types.ts, widget/embedded/src/constants/index.ts, widget/ui/src/components/StepDetails/StepDetails.styles.ts, widget/ui/src/components/StepDetails/StepDetails.tsx, widget/ui/src/components/StepDetails/StepDetails.types.ts
* Add internalSwap for each step.
* Show title for each swapper base on swaper type.
* Add background color for each step
* Fix alerts for each step 
* Link swapper details to scanner
=> fix: fix swap detail style issues

docs/prerelease.md
This doc will be completed after our first release by our new scripts. the final goal is having a documented process to release the production.
=> docs: adding a prerelese doc

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/Layout/Layout.styles.ts, widget/embedded/src/components/Layout/Layout.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsCompleteModal.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.tsx, widget/embedded/src/components/WalletModal/WalletModal.tsx, widget/embedded/src/constants/index.ts, widget/embedded/src/index.ts, widget/embedded/src/pages/Home.tsx, widget/embedded/src/store/slices/config.ts, widget/embedded/src/types/config.ts, widget/embedded/src/utils/common.ts, widget/ui/src/components/ChainToken/ChainToken.tsx, widget/ui/src/components/ChainToken/ChainToken.types.ts, widget/ui/src/components/common/Image.tsx, widget/ui/src/constants/index.ts, widget/ui/src/containers/SwapInput/SwapInput.tsx, widget/ui/src/containers/SwapInput/TokenSection.tsx, widget/ui/src/containers/SwapInput/TokenSection.types.ts, widget/ui/src/index.ts
Applied Leshka friendly styles and configs to widget.
Fixes # 1208
Please refer to the PR at [https://github.com/rango-exchange/leshka-app/pull/3](https://github.com/rango-exchange/leshka-app/pull/3) for detailed testing steps and guidance.
=> feat: Adding title to config and export IDs for accessing blockchain image and swap input

widget/embedded/readme.md
The readme of widget/embedded is updated.
=> chore: update readme.md

widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/HeaderButtons/HomeButtons.tsx, widget/embedded/src/components/NotificationContent/NotificationContent.styles.ts, widget/embedded/src/components/Quote/Quote.tsx, widget/ui/src/components/BlockchainsChip/BlockchainsChip.styles.ts, widget/ui/src/components/NotFound/NotFound.styles.ts, widget/ui/src/containers/SwapInput/TokenSection.styles.ts
fixed bugs in widget on small screens
=> fix: widget ui bugs

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/Layout/Layout.styles.ts, widget/embedded/src/components/Layout/Layout.tsx, widget/embedded/src/components/Layout/Layout.types.ts, widget/embedded/src/components/Quote/QuoteCostDetails.tsx, widget/embedded/src/components/QuoteWarningsAndErrors/HighValueLossWarningModal.tsx, widget/embedded/src/components/QuoteWarningsAndErrors/SlippageWariningModal.tsx, widget/embedded/src/components/QuoteWarningsAndErrors/UnknownPriceWarningModal.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsCompleteModal.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.tsx, widget/embedded/src/components/WalletModal/WalletModal.tsx, widget/embedded/src/components/common/ActivateTabModal/ActivateTabModal.tsx, widget/embedded/src/components/common/WatermarkedModal/WatermarkedModal.tsx, widget/embedded/src/components/common/WatermarkedModal/index.ts, widget/embedded/src/containers/App/App.tsx, widget/embedded/src/hooks/useFetchApiConfig.ts, widget/embedded/src/pages/Home.tsx, widget/embedded/src/store/ui.ts, widget/playground/src/components/ExportConfigModal/ExportConfigModal.tsx, widget/ui/src/components/Modal/Modal.styles.ts, widget/ui/src/components/Modal/Modal.tsx, widget/ui/src/components/Modal/Modal.types.ts, widget/ui/src/components/Modal/index.ts
There is a new API to get a list of features based on API key. There is only one feature for now that is showing Powered By... or not. but it can be includes more options in future.
Verify that the API is being called appropriately. If the response is NONE, the watermark "Powered By" should not appear; if it is FULL, the watermark should appear.
Be sure to review every page and modal.
=> feat: feature management from server

widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.WalletState.tsx, widget/embedded/src/hooks/useWalletList.ts, widget/embedded/src/pages/WalletsPage.tsx, widget/embedded/src/utils/wallets.ts
Reverts rango-exchange/rango-client#517
=> revert: fix connecting wallet issue

widget/playground/src/components/SideNavigation/SideNavigation.Tabs.tsx, widget/playground/src/components/SideNavigation/SideNavigation.styles.ts, widget/playground/src/constants/presets.ts, widget/playground/src/containers/StyleLayout/StyleLayout.CustomColors.tsx, widget/playground/src/containers/StyleLayout/StyleLayout.General.tsx, widget/playground/src/containers/StyleLayout/StyleLayout.styles.ts, widget/playground/src/containers/configContainer/ConfigContainer.styles.ts, widget/playground/src/containers/configContainer/ConfigContainer.tsx, widget/ui/src/components/Typography/NotSelectableTypography.ts, widget/ui/src/components/Typography/index.ts
Tested this by running playground on Chrome browser and checking each of listed items.
=> fix: apply playground improvements

global-wallets-env.d.ts, wallets/provider-math-wallet/package.json, wallets/provider-math-wallet/src/helpers.ts, wallets/provider-math-wallet/src/index.ts, wallets/provider-math-wallet/src/signer.ts, wallets/provider-math-wallet/src/signers/cosmosSigner.ts, wallets/shared/src/rango.ts, yarn.lock
Implemented Cosmos connect account and sign transaction for Math Wallet using CosmJs library.
=> feat: add cosmos account and signer for math wallet

widget/playground/src/containers/configContainer/ConfigContainer.styles.ts, widget/playground/src/containers/configContainer/ConfigContainer.tsx
Added animation to playground widget guide show/hide.
Fixes # 1239
Tested this by running playground on Chrome browser and checking show/hide widget guide functionality.
=> feat: add animation to playground widget guide show/hide

widget/ui/src/components/Toast/Toast.helpers.ts, widget/ui/src/components/Toast/Toast.styles.ts, widget/ui/src/components/Toast/Toast.tsx
A transition is added to the toast component. it changed to transform instead of opacity.
You can test it by storybook. Or linking this PR to alpha branch of dapp.
=> feat: add animation to toast

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsCompleteModal.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.Cancel.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.Delete.tsx, widget/embedded/src/pages/Home.tsx, widget/ui/src/components/Modal/Modal.tsx, widget/ui/src/components/TextField/TextField.styles.ts
Fixes # 1230
Tested this by running widget on Chrome and Firefox browsers and checking each of listed items.
=> fix: fix widget ui minor bugs

wallets/provider-math-wallet/package.json, yarn.lock
=> fix: fix cosmjs incompatible dependency version problem

.gitignore, .npmrc, package.json
Enforcing using yarn package manager.
Try run `npm install`, it should fails.
=> chore: enforcing use yarn

.husky/commit-msg, commitlint.config.js, package.json, yarn.lock
Lint commits to ensure they are conventional commits.
Fixes RF-1314
First you need to run `yarn` to install the git hook.
then try to break the rules by committing invalid message format.
=> chore: add commitlint

widget/embedded/src/constants/quote.ts, widget/embedded/src/pages/Routes.tsx, widget/ui/src/components/Select/Select.tsx, widget/ui/src/components/Select/select.styles.ts
User could change sort preference in routes page.
(Added sort filter for multi routing)
=> feat: add filter for multi-routing sort preference

wallets/provider-bitget/src/index.ts, wallets/readme.md
I just quickly checked supported wallets by rango to make sure they are up to date.
=> chore: update wallets docs

wallets/provider-xdefi/package.json, wallets/provider-xdefi/src/constants.ts, wallets/provider-xdefi/src/cosmos-signer.ts, wallets/provider-xdefi/src/helpers.ts, wallets/provider-xdefi/src/index.ts, wallets/provider-xdefi/src/signer.ts, wallets/readme.md, wallets/shared/src/rango.ts
Attempted to add new chains to XDEFI wallet. The status of each chain is indicated below.
- Dash: Not supported!
- Doge: Added get accounts and signer. Tested by swapping from DOGE Doge to RUNE Thorchain.
- Maya: Added get accounts and signer. Tested by swapping from CACAO Maya to RUNE Thorchain.
- Tron: Could not find any injected provider.
- Cosmos: Added get accounts and signer. Tested by swapping from OSMO Osmosis to ATOM Cosmos.
Fixes RF-1286
=> feat: add new chains to xdefi

.husky/commit-msg
Fix husky's commit-msg hook on windows.
=> chore: fix commit-msg hook

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWallets.styles.ts, widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/LoadingLiquiditySourceList/LoadingLiquiditySourceList.styles.ts, widget/embedded/src/components/LoadingLiquiditySourceList/LoadingLiquiditySourceList.tsx, widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/components/Quote/QuoteTrigger.tsx, widget/embedded/src/components/Slippage/Slippage.tsx, widget/embedded/src/pages/ConfirmSwapPage.tsx, widget/embedded/src/pages/LiquiditySourcePage.tsx, widget/embedded/src/pages/SettingsPage.tsx, widget/embedded/src/utils/ui.ts, widget/ui/src/components/ListItem/ListItem.types.ts, widget/ui/src/components/ListItemButton/ListItemButton.styles.ts, widget/ui/src/components/ListItemButton/ListItemButton.tsx, widget/ui/src/components/ListItemButton/ListItemButton.types.ts
Fix console warning in rango-client
There shouldn't be a warning message on the console.
Check every page.
=> fix: fix console warning in widget

widget/embedded/src/components/HeaderButtons/HeaderButtons.styles.ts, widget/embedded/src/components/HeaderButtons/RefreshButton.tsx, widget/embedded/src/components/HeaderButtons/WalletButton.tsx, widget/embedded/src/containers/Settings/Lists.tsx, widget/ui/src/components/Tooltip/Tooltip.styles.ts
widget ui bug fixes & improvement
=> fix: fix widget ui bug fixes & improvement

widget/embedded/package.json, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.WalletState.tsx, widget/embedded/src/constants/index.ts, widget/embedded/src/hooks/useWalletList.ts, widget/embedded/src/pages/ConfirmSwapPage.tsx, widget/playground/package.json
=> fix: minor bug fixes in widget

widget/embedded/src/containers/App/App.tsx, widget/embedded/src/containers/Widget/Widget.tsx
I18nManager unmount its children after changing language which leads to reset MemoryRouter as well.
=> fix: fix unmounting router on changing language

widget/embedded/src/components/Quote/QuoteTrigger.tsx, widget/embedded/src/components/Quotes/SelectStrategy.tsx, widget/embedded/src/constants/quote.ts, widget/embedded/src/hooks/useScreenDetect.ts, widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.Skeletons.tsx
=> fix: minor bug fixes in widget ui

widget/embedded/src/store/slices/config.ts
Added a default variant to config store
=> fix: add a default variant to widget config store

widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/containers/Inputs/Inputs.tsx, widget/embedded/src/containers/Settings/Lists.tsx, widget/embedded/src/pages/Home.tsx, widget/embedded/src/store/slices/data.ts, widget/embedded/src/utils/numbers.ts, widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.Skeletons.tsx, widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.styles.ts, widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.tsx, widget/ui/src/components/PriceImpact/PriceImpact.tsx, widget/ui/src/components/PriceImpact/PriceImpact.types.ts
=> fix: fix ui and some logic bugs

widget/embedded/src/components/Layout/Layout.tsx, widget/embedded/src/components/RefreshModal/index.ts
There was a problem with export refresh modal, which was fixed in this PR
=> fix: fix export refresh modal 

docs/test.md, package.json, widget/embedded/package.json, widget/embedded/src/store/slices/data.test.ts, widget/embedded/src/test-utils/fixtures.ts, yarn.lock
**vitest** is configured to work with **zustand** And a series of unit tests for the App Store have been added to the widget
You can run the `yarn test` command and all the tests should pass correctly.
To see more details, you can enter the embedded project with the `cd widget/embedded/` command and run the `yarn test ` command again.
=> feat: add unit test for app store

signers/signer-solana/src/utils/main.ts, wallets/provider-coin98/package.json, wallets/provider-walletconnect-2/package.json, yarn.lock
=> fix: fix solana rejection error code

global-wallets-env.d.ts, wallets/core/src/wallet.ts, wallets/provider-coinbase/src/helpers.ts, wallets/provider-coinbase/src/index.ts, wallets/provider-metamask/src/helpers.ts, wallets/provider-xdefi/src/helpers.ts, wallets/provider-xdefi/src/index.ts, wallets/shared/src/helpers.ts
it can be tested by installing `xdefi`, `taho`, `coinbase` and `metamask` .
=> fix: address xdefi prioritization issue

queue-manager/rango-preset/src/shared.ts, wallets/provider-okx/src/helpers.ts, widget/embedded/src/components/ConfirmWalletsModal/ConfirmWallets.styles.ts, widget/embedded/src/components/CustomCollapsible/CustomCollapsible.styles.ts, widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.tsx, widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.types.ts, widget/embedded/src/components/RefreshModal/RefreshModal.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.styles.ts, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/components/TokenList/TokenList.styles.ts, widget/embedded/src/components/TokenList/TokenList.tsx, widget/embedded/src/pages/ConfirmSwapPage.tsx, widget/embedded/src/pages/Home.tsx
By comparing my changes for each item with related figma.
=> fix: fix widget ui bugs

widget/embedded/src/components/HeaderButtons/WalletButton.tsx
fixing wallet connect project id
linking with Dapp and click on wallet connect in modal
=> fix: address passing wallet-connect project id

widget/playground/src/App.tsx, widget/playground/src/containers/StyleLayout/StyleLayout.Preset.tsx
Sync playground theme with widget
With the change of playground theme, the widget theme should also be changed
=> feat: sync playground theme with widget

signers/signer-solana/src/index.ts, signers/signer-solana/src/utils/index.ts, signers/signer-solana/src/utils/main.ts, signers/signer-solana/src/utils/simulate.ts, wallets/provider-all/package.json, wallets/provider-all/src/index.ts, wallets/provider-solflare-snap/package.json, wallets/provider-solflare-snap/readme.md, wallets/provider-solflare-snap/src/helpers.ts, wallets/provider-solflare-snap/src/index.ts, wallets/provider-solflare-snap/src/signer.ts, wallets/provider-solflare-snap/src/signers/solanaSigner.ts, wallets/provider-solflare-snap/tsconfig.json, wallets/readme.md, wallets/shared/src/rango.ts, yarn.lock
Added Solflare Snap connect and signer.
Fixes # 1383
Tested by connecting to Solflare Snap and signing a transaction.
=> feat: add solflare snap connect and signer

package.json, wallets/provider-all/package.json, wallets/provider-all/src/index.ts, wallets/provider-ledger/package.json, wallets/provider-ledger/readme.md, wallets/provider-ledger/src/helpers.ts, wallets/provider-ledger/src/index.ts, wallets/provider-ledger/src/signer.ts, wallets/provider-ledger/src/signers/ethereum.ts, wallets/provider-ledger/tsconfig.json, wallets/readme.md, wallets/shared/src/rango.ts, yarn.lock
Added Ledger connect and signer.
=> feat: add ledger connect and signer

examples/queue-manager-demo/package.json, examples/queue-manager-demo/src/flows/rango/helpers.ts, wallets/provider-xdefi/src/index.ts
=> Fix build queue manager demo example error

.github/workflows/checks.yaml, scripts/build-libs/command.mjs, scripts/build/command.mjs, scripts/common/utils.mjs, widget/embedded/src/hooks/usePrepareBlockchainList/usePrepareBlockchainList.test.ts
Running project tests was also added to the check workflow.
From now on, for each PR that is opened, in addition to the conventional commit, test files are also run, and if all tests pass, the check workflow is confirmed.
Also, before running the tests, we build all the libraries, and in the build process, the types are also checked, to make sure that all the libraries work correctly.
To test, you can get a new branch from this branch.
And open a new PR and see the new check workflow processes, i.e. building projects and running tests.
=> feat: add test to check workflow

.github/workflows/checks.yaml
=> chore: fix vercel build

widget/embedded/src/components/Quote/Quote.styles.ts, widget/embedded/src/components/Quote/Quote.tsx
Added hover style to "all routes" button.
Fixes #RF-1420
=> feat: add hover style to all routes button

widget/embedded/src/pages/Home.tsx
Fix space between of routes and swap box in expanded mode
Check in Codesandbox
=> fix: fix space between of routes and swap box in expanded mode

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/utils/meta.ts, widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.tsx
Minor improvements in widget embedded
1.  Fix wrong animation when changing wallets in confirm wallet
2.  Show a better message for bridge limit error and slippage warning
3.  Fix swapper in full expanded => show swapper title instead of swapper group
=> fix : minor improvements

wallets/provider-all/package.json, widget/embedded/src/hooks/useWalletList.ts
Fixed bug in checking initial value of multiWallets config.
Open playground in a private page and try to connect more than one wallets.
=> fix: fix multiwallets config initial value check bug

signers/signer-solana/src/utils/helpers.ts
We are switching to a new account for our Solana RPC.
=> chore: update solana default rpc url

CHANGELOG.md, widget/app/package.json, widget/playground/package.json
=> chore(release): deploy

docs/release.md
=> chore: update release doc

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWallets.styles.ts, widget/embedded/src/components/HeaderButtons/HeaderButtons.styles.ts, widget/embedded/src/components/Quote/Quote.styles.ts, widget/playground/src/components/MultiSelect/MultiSelect.styles.ts, widget/playground/src/components/TokensPanel/TokensPanel.styles.ts, widget/ui/src/components/BlockchainsChip/BlockchainsChip.styles.ts, widget/ui/src/components/ChainToken/ChainToken.styles.ts, widget/ui/src/components/ChainToken/ChainToken.tsx, widget/ui/src/components/Chip/Chip.styles.ts, widget/ui/src/components/ListItemButton/ListItemButton.styles.ts, widget/ui/src/components/MessageBox/CollapsibleMessageBox.styles.tsx, widget/ui/src/components/PriceImpact/PriceImpact.tsx, widget/ui/src/components/Select/Select.styles.ts, widget/ui/src/components/SwapListItem/SwapListItem.styles.ts, widget/ui/src/components/Tabs/Tabs.styles.tsx, widget/ui/src/components/TextField/TextField.styles.ts, widget/ui/src/components/Toast/Toast.styles.ts, widget/ui/src/components/Wallet/Wallet.styles.ts, widget/ui/src/containers/SwapInput/SwapInput.styles.ts, widget/ui/src/containers/SwapInput/SwapInput.tsx, widget/ui/src/containers/SwapInput/TokenSection.styles.ts, widget/ui/src/containers/SwapInput/TokenSection.tsx, widget/ui/src/theme.ts
Update design for not-selected blockchain or token (and color hover has been updated based on Figma.) 
=> fix: update design for not-selected blockchain or token

widget/embedded/src/components/Slippage/Slippage.tsx
Resolved bugs in custom slippage input.
Fixes # RF-1521
You can test this by entering different values in custom slippage input.
=> fix: resolve custom slippage bug

.github/workflows/checks.yaml, package.json, scripts/analyze-bundle/command.mjs, scripts/analyze-bundle/compare.mjs, scripts/analyze-bundle/downloadTargetBranchArtifacts.mjs, scripts/analyze-bundle/findBuildFiles.mjs, scripts/build/command.mjs, scripts/common/constants.mjs, yarn.lock
Include a workflow check to analyze the widget bundle.
Utilize a package such as Material UI within the widget and submit your changes to this pull request. The workflow will execute and display the alteration in the widget bundle's size.
=> chore: add analyze bundle workflow

.github/actions/upload-build-artifacts/action.yml, .github/workflows/checks.yaml
eliminate any newline characters from the artifact names
=> chore: eliminate any newline characters from the artifact names

.github/actions/upload-build-artifacts/action.yml, .github/workflows/checks.yaml, .github/workflows/upload-build-artifacts.yml
A few name updates to make sure all the names using same convetion.
=> chore: update names to be matched with other workflows

docs/prerelease.md, docs/release.md
[skip ci]
Updated sandbox url and improved release notes.
=> chore: update release docs

queue-manager/rango-preset/src/index.ts, widget/embedded/src/components/NotificationContent/NotificationContent.tsx, widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/components/Quotes/Quotes.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.helpers.ts, widget/embedded/src/containers/WidgetInfo/WidgetInfo.tsx, widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.helpers.ts, widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.ts, widget/embedded/src/hooks/useSubscribeToWidgetEvents/useSubscribeToWidgetEvents.ts, widget/embedded/src/hooks/useSwapInput.ts, widget/embedded/src/hooks/useSyncStoresWithConfig.ts, widget/embedded/src/hooks/useSyncUrlAndStore/useSyncUrlAndStore.helpers.ts, widget/embedded/src/hooks/useSyncUrlAndStore/useSyncUrlAndStore.ts, widget/embedded/src/store/quote.ts, widget/embedded/src/store/selectors.ts, widget/embedded/src/store/slices/data.test.ts, widget/embedded/src/store/slices/data.ts, widget/embedded/src/store/wallets.ts, widget/embedded/src/test-utils/fixtures.ts, widget/embedded/src/utils/meta.ts, widget/embedded/src/utils/quote.ts, widget/embedded/src/utils/swap.ts, widget/embedded/src/utils/wallets.ts
Eliminate the use of tokens.find() in the embedded widget to enhance performance
=> perf: improve finding tokens from store

wallets/shared/src/rango.ts, widget/embedded/src/components/WalletNamespacesModal/WalletNamespacesModal.tsx
These changes are related to [this ](https://github.com/rango-exchange/app-v2/pull/12)PR.
=> chore: improve some types

wallets/provider-all/package.json, wallets/provider-all/src/index.ts, wallets/provider-rabby/package.json, wallets/provider-rabby/readme.md, wallets/provider-rabby/src/helpers.ts, wallets/provider-rabby/src/index.ts, wallets/provider-rabby/src/signer.ts, wallets/provider-rabby/tsconfig.json, wallets/readme.md, wallets/shared/src/rango.ts, yarn.lock
integrate rabby wallet extension
Fixes # 1496
Tested by installing Rabby wallet extension on Chrome browser and signing a transaction on BSC.
=> feat: integrate rabby wallet extension

global-wallets-env.d.ts, wallets/provider-all/package.json, wallets/provider-all/src/index.ts, wallets/provider-tomo/package.json, wallets/provider-tomo/readme.md, wallets/provider-tomo/src/helpers.ts, wallets/provider-tomo/src/index.ts, wallets/provider-tomo/src/signer.ts, wallets/provider-tomo/tsconfig.json, wallets/readme.md, wallets/shared/src/rango.ts
In this PR, I've added support for Tomo wallet extension for the EVM blockchains. This wallet doesn't have document for cosmos yet and it's interface is not fully compatible with Keplr, so we don't integrate its cosmos yet.
By installing Tomo extension and testing different scenarios including signing the transaction, switch network and so on.
=> feat: support tomo wallet

queue-manager/rango-preset/package.json, queue-manager/rango-preset/src/configs.ts, queue-manager/rango-preset/src/hooks.ts, queue-manager/rango-preset/src/index.ts, queue-manager/rango-preset/src/services/eventEmitter.ts, queue-manager/rango-preset/src/types.ts, widget/embedded/src/QueueManager.tsx, widget/embedded/src/hooks/useBootstrap/useBootstrap.ts, widget/embedded/src/hooks/useSubscribeToWidgetEvents/useSubscribeToWidgetEvents.ts, widget/embedded/src/hooks/useSyncStoresWithConfig.ts, widget/embedded/src/hooks/useWidgetEvents/index.ts, widget/embedded/src/hooks/useWidgetEvents/useWidgetEvents.ts, widget/embedded/src/index.ts, widget/embedded/src/services/eventEmitter.ts, widget/embedded/src/store/quote.ts, widget/embedded/src/store/wallets.ts, widget/embedded/src/types/event.ts, widget/embedded/src/types/index.ts
Added support for some new Quote and Wallet events.
Fixes # RF-1569
You can test it by adding the below code in the following path: `widget/app/src/App.tsx`
```
import { useWidgetEvents, Widget } from '@rango-dev/widget-embedded';
const eventEmitter = useWidgetEvents();
useEffect(() => {
const handleEvent = (event: any) => {
console.log('WalletEvent', event);
};
eventEmitter.on(MainEvents.WalletEvent, handleEvent);
return () => eventEmitter.off(MainEvents.WalletEvent, handleEvent);
}, [eventEmitter]);
useEffect(() => {
const handleEvent = (event: any) => {
console.log('QuoteEvent', event);
};
eventEmitter.on(MainEvents.QuoteEvent, handleEvent);
return () => eventEmitter.off(MainEvents.QuoteEvent, handleEvent);
}, [eventEmitter]);
useEffect(() => {
const handleEvent = (event: any) => { …
```
=> feat: support new widget events

widget/embedded/src/hooks/useWalletList.ts, widget/embedded/src/index.ts
We needed to be able to use useWalletList in the dapp
=> feat: export useWalletList for use in dapp

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/TokenList/TokenList.tsx, widget/embedded/src/hooks/useSubscribeToWidgetEvents/useSubscribeToWidgetEvents.ts, widget/embedded/src/hooks/useWalletProviders/index.ts, widget/embedded/src/hooks/useWalletProviders/useWalletProviders.helpers.ts, widget/embedded/src/hooks/useWalletProviders/useWalletProviders.ts
On the select token page, if two blockchains have the same number of tokens, switching between them will not update the token list.
We need to improve the values in the `useEffect` dependency array to update the token list when the selected blockchain changes. Additionally, we should review other sections in the widget embedded package to prevent similar issues in the future.
Test the widget-embedded package using this configuration object: 
```
{
from: {
blockchains: [
'ETH',
'BSC'
],
tokens: {
ETH: {
isExcluded: false,
tokens: [
{
symbol: 'USDT',
address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
blockchain: 'ETH'
},
{
symbol: 'USDC',
address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
blockchain: 'ETH'
}
]
},
BSC: {
isExcluded: false,
tokens: [
{
symbol: 'BCH', …
```
=> fix `useEffect` bug in the token selector

widget/embedded/src/components/TokenList/TokenList.tsx, widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.tsx, widget/ui/src/components/PriceImpact/PriceImpact.styles.ts, widget/ui/src/components/PriceImpact/PriceImpact.tsx, widget/ui/src/components/TokenAmount/TokenAmount.tsx
1. The labels' color should have been a better fit
2. The price/amount colors should be fixed.
=> fix: improved generate colors for tokens label and price impact color

widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.helpers.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/ui/src/components/StepDetails/StepDetails.types.ts, widget/ui/src/containers/SwapInput/TokenSection.styles.ts
Fix relative import issue in widget ui files.
=> fix: fix import issue in ui

wallets/provider-trezor/src/helpers.ts, wallets/provider-trezor/src/index.ts, wallets/provider-trezor/src/signers/ethereum.ts
@trezor/connect-web is commonjs, there are some tools differences when importing it dynamically. For instance, vue and vite and etc throws an error
=> fix: import Trezor module

CHANGELOG.md, widget/app/package.json, widget/playground/package.json
=> chore: update changelog

widget/embedded/src/hooks/useTheme.ts
Fixed a flicker that was happening in playground when navigating between pages in widget.
Fixes # rf-1611
Tested by navigating between widget pages in playground.
=> fix: fix flicker in playground

widget/ui/src/components/TokenAmount/TokenAmount.styles.ts, widget/ui/src/components/TokenAmount/TokenAmount.tsx
Fixed a price wrong alignment.
Fixes # 1666
Navigated to swap details page and saw price alignment is fixed.
=> fix: fix swap input price alignment

wallets/provider-ledger/src/helpers.ts, wallets/provider-trezor/src/helpers.ts, wallets/provider-trezor/src/index.ts, wallets/provider-trezor/src/signers/ethereum.ts, wallets/provider-trezor/src/state.ts, widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.WalletState.tsx, widget/embedded/src/pages/WalletsPage.tsx
Added derivation path modal for Trezor wallet.
Fixes # 1633
Tested by connecting to Trezor wallet on different paths on Ethereum chain (EVM namespace) and signing transactions.
=> feat: add derivation path modal for trezor wallet

widget/embedded/src/containers/WidgetInfo/WidgetInfo.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.types.ts, widget/embedded/src/hooks/useUpdateQuoteInput/index.ts, widget/embedded/src/hooks/useUpdateQuoteInput/useUpdateQuoteInput.ts, widget/embedded/src/types/quote.ts
We are looking to update the quote inputs from outside the widget, but using widget configuration does not always produce the desired results.
=> feat: add functionality to update the quote inputs from outside the widget

widget/playground/src/containers/configContainer/ConfigContainer.Header.tsx, widget/ui/src/components/Modal/Modal.styles.ts, widget/ui/src/components/Modal/Modal.tsx, widget/ui/src/components/Modal/Modal.types.ts
Fixed a lag in modal animation.
Fixes #1661
The problem was emerged in connect wallet modal in dapp so I linked "@rango-dev/ui" in app project and tested openning and closing that modal.
=> fix: fix modal animation

global-wallets-env.d.ts, signers/signer-solana/src/index.ts, signers/signer-solana/src/utils/index.ts, signers/signer-solana/src/utils/main.ts, wallets/provider-all/package.json, wallets/provider-all/src/index.ts, wallets/provider-solflare/package.json, wallets/provider-solflare/readme.md, wallets/provider-solflare/src/index.ts, wallets/provider-solflare/src/signer.ts, wallets/provider-solflare/src/signers/solanaSigner.ts, wallets/provider-solflare/tsconfig.build.json, wallets/provider-solflare/tsconfig.json, wallets/readme.md, wallets/shared/src/rango.ts, yarn.lock
Integrated Solflare wallet.
Fixes # 1468
Tested by connecting and signing transaction on Solflare wallet extension.
=> feat: integrate solflare wallet

widget/ui/src/components/Modal/Modal.styles.ts, widget/ui/src/components/Modal/Modal.tsx, widget/ui/src/components/Modal/Modal.types.ts
Fix bug in modal animation. The bug was related to an unpredicted speed for modal transitions.
Fixes # 1753
Part of this bug was related to [this](https://github.com/rango-exchange/rango-client/pull/796) Pull Request.
Tested every modal in widget and playground.
=> fix: fix bug in modal animation

widget/embedded/package.json
=> hotfix: update embedded version

widget/embedded/src/index.ts
Export a new hook to handle stateful connect (namespace and derivation path)
We already [merged a PR](https://github.com/rango-exchange/rango-client/pull/821) to add this feature, this PR only exporting the hook to be used in our dApp.
It doesn't need to be tested, since it's only exporting something that already exists.
=> feat: export a new hook for handling required data for connect called useStatefulConnect

widget/embedded/src/components/StatefulConnectModal/StatefulConnectModal.tsx, widget/embedded/src/components/WalletStatefulConnect/DerivationPath.tsx, widget/embedded/src/hooks/useStatefulConnect/useStatefulConnect.ts
Fix stuck at connecting and reset derivation path value on custom mode.
RF-1684 and RF-1710 have 2 reported bugs that fixed in this PR.
=> fix: some fixes for refactoring modal

widget/embedded/src/components/WalletStatefulConnect/DerivationPath.tsx, widget/embedded/src/hooks/useFetchCustomToken.ts
Translation errors were corrected
=> fix: correct translation bugs

examples/queue-manager-demo/package.json, examples/wallets-adapter-demo/package.json, examples/wallets-demo/package.json, wallets/provider-all/CHANGELOG.md, wallets/provider-all/package.json, wallets/provider-all/src/index.ts, wallets/provider-trezor/CHANGELOG.md, wallets/provider-trezor/notes.md, wallets/provider-trezor/package.json, wallets/wallets-adapter/CHANGELOG.md, wallets/wallets-adapter/package.json, widget/app/package.json, widget/embedded/CHANGELOG.md, widget/embedded/package.json, widget/iframe/package.json, widget/playground/package.json
Update `next` with latest changes on `main` (includes Trezor hotfix).
=> chore: sync next with main

widget/embedded/src/components/BlockchainList/BlockchainList.tsx, widget/embedded/src/components/BlockchainsSection/BlockchainsSection.tsx, widget/embedded/src/components/HeaderButtons/HeaderButtons.tsx, widget/embedded/src/components/Slippage/SlippageTooltipContent.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.Placeholder.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/components/WalletStatefulConnect/ExperimentalChain.tsx, widget/embedded/src/components/WalletStatefulConnect/ExperimentalChainStatus.helpers.ts, widget/embedded/src/components/WalletStatefulConnect/ExperimentalChainStatus.tsx, widget/embedded/src/containers/Settings/Lists.tsx, widget/embedded/src/hooks/useFetchCustomToken.ts, widget/embedded/src/pages/HistoryPage.tsx, widget/embedded/src/pages/LanguagePage.tsx, widget/embedded/src/pages/SelectBlockchainPage.tsx, widget/playground/src/components/MultiSelect/MultiSelect.types.ts, widget/playground/src/containers/DefaultChainAndToken/DefaultChainAndToken.tsx, widget/playground/src/containers/SupportedBlockchains/SupportedBlockchains.tsx
In this PR, I've updated warning messages in widget.
Fixes RF-1871
By checking related section specially adding experimental chain.
Also, we shouldn't use Blockchain anymore.
=> chore: improve warning messages and titles

wallets/shared/src/getCosmosAccounts.ts
We had an error connecting the cosmostation wallet
=> fix: cosmostation wallet connection error

signers/signer-solana/src/utils/prepare.ts
RF-1867: We need to update versioned transactions using signatures similar to legacy transactions to support signing by multi-signatures provided by API.
Since API is not live yet, this PR is tested by the backend team. But you could test previous models of Solana transaction to make sure nothing breaks.
```bash
yarn
yarn dev:widget
```
=> feat: add signature to versioned transactions

widget/charts/src/components/BarChart/BarChart.constants.ts, widget/charts/src/components/BarChart/BarChart.helpers.ts, widget/charts/src/components/BarChart/BarChart.styles.ts, widget/charts/src/components/BarChart/BarChart.tsx, widget/charts/src/components/BarChart/BarChart.types.ts, widget/charts/src/components/BarChart/index.ts, widget/charts/src/index.ts
add prepareBarChartData function in chart package
=> feat: add prepareBarChartData function in chart package

examples/queue-manager-demo/package.json, examples/wallets-adapter-demo/package.json, examples/wallets-demo/package.json, wallets/provider-all/package.json, wallets/provider-xdefi/package.json, wallets/wallets-adapter/package.json, widget/app/package.json, widget/embedded/package.json, widget/iframe/package.json, widget/playground/package.json, yarn.lock
َUpdate internal packages to latest published versions.
During a bug, after merging a [PR for pulling latest updates from main](https://github.com/rango-exchange/rango-client/pull/894), packages didn't publish properly.
=> chore: update internal packages to latest

.github/workflows/prerelease.yml, .github/workflows/release.yml, docs/prerelease.md, docs/release.md
Added prerelease workflow to be run manually before starting release process. It contains running crowding workflow and deployment on the next branch.
=> chore: add prerelease workflow

examples/wallets-adapter-demo/package.json, examples/wallets-demo/package.json, wallets/wallets-adapter/package.json, widget/app/package.json, widget/charts/package.json, widget/embedded/package.json, widget/iframe/package.json, widget/playground/package.json, widget/storybook/package.json
=> chore: upgrade all

widget/ui/readme.md
Trigger an update for re-publish ui package.
=> chore: update UI README

.github/workflows/prerelease.yml
There was a problem in prerelease workflow deployment in result of not fetching the latest crowdin changes. A step is added to pull the latest changes from next branch and fix that issue.
=> chore: fix prerelease workflow issue with crowdin

wallets/provider-all/src/helpers.ts, wallets/provider-all/src/index.ts, wallets/provider-phantom/src/legacy/index.ts, wallets/provider-phantom/src/mod.ts, wallets/provider-phantom/src/provider.ts, wallets/react/src/hub/useHubRefs.ts, wallets/react/src/hub/utils.ts, wallets/react/src/index.ts, widget/embedded/src/hooks/useWalletList.ts, widget/embedded/src/hooks/useWalletProviders/useWalletProviders.ts, widget/embedded/src/store/slices/config.ts, widget/embedded/src/store/slices/data.test.ts, widget/embedded/src/utils/providers.ts, widget/playground/src/App.tsx, widget/playground/src/containers/FunctionalLayout/FunctionalLayout.Wallets.tsx
Fixed bugs on hub not being compatible with external wallets.
=> fix: make hub compatible with external wallets

signers/signer-solana/src/config.ts, signers/signer-solana/src/index.ts, signers/signer-solana/src/utils/helpers.ts, signers/signer-solana/src/utils/index.ts, signers/signer-solana/src/utils/main.ts, signers/signer-solana/src/utils/send.ts, signers/signer-solana/src/utils/simulate.ts, signers/signer-solana/src/utils/types.ts, wallets/provider-solflare-snap/src/signers/solanaSigner.ts, widget/embedded/src/types/config.ts
Added extra Solana RPC URLs to increase success rate of send Solana transactions.
=> feat: add sending solana transaction on multiple nodes

widget/embedded/src/components/SwapDetailsModal/SwapDetailsCompleteModal.tsx
Due to the image change on the asset side and the different image format, this needed to be updated here
=> fix: updated profile banner format from png to jpg

wallets/react/helpers/package.json, wallets/react/package.json, wallets/react/src/helpers/index.ts, wallets/react/src/index.ts, widget/playground/src/containers/FunctionalLayout/FunctionalLayout.Wallets.tsx, widget/playground/tsconfig.build.json
Improved `@rango-dev/wallets-react` interface by exporting helpers and moving `getAllLegacyProviders` to helpers.
=> chore: improve wallets-react interface

scripts/common/git.mjs
=> chore: update git.mjs

widget/embedded/src/store/slices/wallets.ts
Explorer URL was not getting updated on connected wallets in wallets slice after fetching details for wallets. In this PR, after fetching details for wallets, explorer URL gets updated. It is required for go to account button in `walletDetails` of app.
This can be tested on app (after linking this changes to "upgrade to hub" PR on APP) by clicking on go to account button in wallet details sidebar.
=> fix: update explorer url on connected wallets

widget/ui/src/components/Wallet/ClickableWallet.tsx
There was an error in `ClickableWallet` component related to incorrect props being supplied to `Fragment` component which is resolved in this PR.
=> fix: resolve error in clickable wallet component

widget/embedded/src/components/SwapDetailsModal/SwapDetailsCompleteModal.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.styles.ts, widget/embedded/src/constants/profileBanner.ts
Added navigation link to Profile Banner.
=> feat: add link to profile banner

queue-manager/rango-preset/src/actions/checkStatus.ts, queue-manager/rango-preset/src/actions/createTransaction.ts, queue-manager/rango-preset/src/actions/scheduleNextStep.ts, queue-manager/rango-preset/src/helpers.ts, queue-manager/rango-preset/src/services/eventEmitter.ts, queue-manager/rango-preset/src/types.ts
=> feat: update the event payload for failed step and failed route events

.github/workflows/checks.yaml
New translation keys were not being compiled in preview deployments, leading to incorrect translations, particularly when dynamic values were used in translation keys. This PR addresses the issue by adding a compilation job after the translation extraction process.
=> fix: fix translation keys not being compiled in preview deployments

CHANGELOG.md, widget/app/package.json, widget/playground/package.json
=> Hot fix/update changelog and versions

widget/embedded/src/components/Layout/Layout.styles.ts
=> fix: fix swap-box banner overflow

widget/embedded/src/components/WalletStatefulConnect/Namespaces.styles.ts, widget/ui/src/components/MessageBox/DefaultMessageBox.tsx
- Added className to title of MessageBox component so it can be accessible from outside of the widget.
- Added a minor style change to namespaces list in namespace selection modal.
=> chore: add classname to message box title and minor style change

widget/ui/src/components/MessageBox/DefaultMessageBox.tsx
Added `className` to description of `MessageBox` component.
=> chore: add class to message box description

wallets/core/src/namespaces/sui/actions.ts, wallets/core/src/namespaces/sui/chains.ts, wallets/core/src/namespaces/sui/mod.ts, wallets/provider-phantom/package.json, wallets/provider-phantom/src/constants.ts, wallets/provider-phantom/src/legacy/index.ts, wallets/provider-phantom/src/legacy/signer.ts, wallets/provider-phantom/src/namespaces/sui.ts, wallets/provider-phantom/src/provider.ts, wallets/provider-phantom/src/utils.ts, widget/app/src/App.tsx
Adds Sui support for phantom.
Fixes RF-2191
1. https://github.com/rango-exchange/rango-types/pull/44
2. https://github.com/rango-exchange/rango-client/pull/1053
3. https://github.com/rango-exchange/rango-client/pull/1054
4. https://github.com/rango-exchange/rango-client/pull/1055
=> feat: sui integration for Phantom

wallets/react/src/hub/useHubAdapter.ts
When filtering wallets in the **Playground** to show only **one Hub wallet**, and there are **more than two Hub wallets available**, the `installed` state of the filtered wallet gets reset to `false`.
This was caused by how `getHub` was implemented in `useHubRefs`:
```ts
function getHub(): Hub {
const hubProviders = hub.current?.getAll();
if (
!hub.current ||
!hubProviders ||
!checkProviderListsEquality(Array.from(hubProviders.values()), providers)
) {
return createHub();
}
return hub.current;
}
```
If the current hub's providers didn’t match the expected list (`providers`), `getHub` recreated the hub using `createHub()`. This added each provider with default values, where `installed: false`. Since the new hub wasn't re-initialized afterward, the installed state remained `false`.
This …
=> Fix: Resetting Installed State on Playground Wallet Filter

queue-manager/rango-preset/src/helpers.ts
I just changed the message to show the network name instead of the namespace.
=> fix: show network name instead of namespace

wallets/provider-phantom/readme.md, wallets/readme.md
* Restructure the main `wallets/README.md`:
* Add the new standardized table at the top.
* Move the existing table below and label it as **Legacy**.
* Use the `phantom` wallet as the first example to implement and validate the updated structure.
=> feat: update readme for wallets and phantom

wallets/shared/src/rango.ts
Added ankr api key to ethereum rpc url to prevent "Unauthorized" errors on rpc calls.
Tested by signing and broadcasting an ethereum transaction using Ledger device.
=> feat: add api key to ethereum rpc url

wallets/core/src/builders/namespace.ts, wallets/core/src/hub/namespaces/namespace.test.ts, wallets/core/src/hub/namespaces/namespace.ts, wallets/core/tests/providers.test.ts, wallets/react/src/hub/useHubAdapter.ts
=> fix: add has method to the namespace proxy (reopened)

wallets/react/src/hub/helpers.ts, wallets/react/src/hub/useHubAdapter.ts
There was an issue when calling connect on multiple namespaces of a provider simultaneously. The root cause was that the useHubAdapter hook exposes a connect method that can be invoked concurrently for different wallet namespaces. Some wallets are unable to handle parallel connection requests, leading to failures during the connection process.
This PR introduces a new custom React hook that manages a controlled, sequential execution queue for asynchronous tasks. This hook ensures that namespace connections are handled one at a time, preventing race conditions or request collisions for wallets that do not support concurrent operations.
Tested by connecting all namespaces on Trust wallet and observing that all of that gets connected properly.
=> fix: run connect namespaces sequentially when connect of adapter called separately

wallets/core/src/namespaces/sui/actions.ts, wallets/core/src/namespaces/sui/builders.ts, wallets/provider-all/package.json, wallets/provider-all/src/index.ts, wallets/provider-slush/package.json, wallets/provider-slush/readme.md, wallets/provider-slush/src/constants.ts, wallets/provider-slush/src/legacy/index.ts, wallets/provider-slush/src/legacy/signer.ts, wallets/provider-slush/src/mod.ts, wallets/provider-slush/src/namespaces/sui.ts, wallets/provider-slush/src/provider.ts, wallets/provider-slush/src/utils.ts, wallets/provider-slush/tsconfig.build.json, wallets/provider-slush/tsconfig.json, wallets/readme.md, wallets/shared/src/rango.ts, yarn.lock
This PR introduces support for integrating the SUI wallet. During integration, a few limitations and issues with the SUI wallet were discovered:
1. **No `onChange` Account Event**  
The wallet does not emit an event when the active account changes, making it difficult to detect account switches programmatically.
2. **Always Connects to First Account**  
Regardless of the selected account in the wallet UI, it always connects to the first account.
Below are the results of testing the SUI wallet integration on various DEX platforms:
- **[Kriya Finance](https://app.kriya.finance/trade)**  
- ❌ Switching account does not work.  
- Always connects to the first wallet account.
- **[Cetus](https://app.cetus.zone/swap)**  
- ❌ Switching account via wallet is not functional.  
- ✅ However, there is …
=> feat: integrate sui wallet

wallets/core/src/namespaces/solana/actions.ts, wallets/core/src/namespaces/solana/utils.ts, wallets/provider-all/src/index.ts, wallets/provider-phantom/readme.md, wallets/provider-trustwallet/package.json, wallets/provider-trustwallet/readme.md, wallets/provider-trustwallet/src/constants.ts, wallets/provider-trustwallet/src/helpers.ts, wallets/provider-trustwallet/src/legacy/index.ts, wallets/provider-trustwallet/src/legacy/signer.ts, wallets/provider-trustwallet/src/mod.ts, wallets/provider-trustwallet/src/namespaces/evm.ts, wallets/provider-trustwallet/src/namespaces/solana.ts, wallets/provider-trustwallet/src/provider.ts, wallets/provider-trustwallet/src/utils.ts, wallets/readme.md
- Migrated **Trust Wallet** to use **Hub**.  
- Added **Solana namespace** support for Trust Wallet.  
- Utilized `canEagerConnect` from **Hub** for improved connection handling.
=> feat: migrate trust wallet to use hub and add support for solana

widget/embedded/src/components/WalletStatefulConnect/NamespaceDetachedItem.tsx
We've encountered an issue in both our **Vite** and **React-JS** widget examples where connect attempts to hub wallets were being triggered **twice**.
This was due to the fact that both examples run in **React Strict Mode**, which intentionally invokes effects **twice** for development-only checks:
* React-JS example: [src/index.js](https://github.com/rango-exchange/widget-examples/blob/fee514b9da60ac9bc4244817ee6b8691e14c8d4b/react-app-rewired-js/src/index.js#L7)
* Vite example: [src/main.tsx](https://github.com/rango-exchange/widget-examples/blob/fee514b9da60ac9bc4244817ee6b8691e14c8d4b/vite/src/main.tsx#L6)
In our component, we use [useLayoutEffect](https://github.com/rango-exchange/rango-client/blob/8fa0459e72c3e6af42c7f9a7bebd08c8f80e9ccc/widget/embedded/src/components/WalletStatefulC …
=> fix: prevent reconnect on strict mode remount

CHANGELOG.md, widget/app/package.json, widget/playground/package.json
Versioned app and playground and updated changelog
=> Hotfix/update changelog v 0.41.0

.github/workflows/postrelease.yml, .github/workflows/prerelease.yml, docs/release.md, scripts/common/git.mjs, scripts/post-release/command.mjs
* **Added a `postrelease` GitHub Actions workflow**.
* **Renamed the Pre-Release workflow** to follow the naming convention used for the `Post-Release` workflow.
* **Updated the `git merge` function** to accept custom commit messages.
=> chore: add post-release workflow

package.json, scripts/common/changelog.mjs, scripts/common/constants.mjs, scripts/common/git.mjs, scripts/common/repository.mjs, scripts/common/typedefs.mjs, scripts/common/version.mjs, scripts/deploy/config.mjs, scripts/publish/command.mjs, scripts/publish/version-log.mjs
This PR updates the publish workflow to:
* Create a version log.
* Bump versions for **root**, **widget**, and **app** packages.
* Generate a changelog for the **root** package.
* Commit the updated versions and changelog back to the repository.
**NOTE:** ***WE HAVE TO PUT THE LATEST VERSION ON ROOT PACKAGE.JSON BEFORE MERGING THIS***
=> chore: modify publish to generate root changelog
