queue-manager/rango-preset/src/index.ts, widget/embedded/src/store/bestRoute.ts, widget/embedded/src/utils/meta.ts, widget/embedded/src/utils/routing.ts
If a swap consists of multiple steps and fails at any one step, the retry mechanism should continue from the failed step and proceed with the remaining steps
=> fix(widget-v2): fix retry logic in failed swaps

wallets/core/src/types.ts, wallets/core/src/wallet.ts, wallets/provider-walletconnect-2/package.json, wallets/provider-walletconnect-2/src/constants.ts, wallets/provider-walletconnect-2/src/helpers.ts, wallets/provider-walletconnect-2/src/index.ts, wallets/provider-walletconnect-2/src/session.ts, wallets/react/src/types.ts, wallets/shared/src/rango.ts, yarn.lock
=> fix(wallets): fix switch network bug in wallet connect

wallets/core/src/wallet.ts, wallets/provider-safe/src/index.ts, wallets/react/src/provider.tsx, wallets/shared/src/rango.ts, widget/embedded/src/Wallets.tsx, widget/embedded/src/utils/wallets.ts
=> fix(widget): fix safe accounts issue

widget/embedded/src/QueueManager.tsx, widget/embedded/src/Wallets.tsx, widget/embedded/src/Widget.tsx, widget/embedded/src/components/AppRouter.tsx, widget/embedded/src/components/BlockchainList/BlockchainList.tsx, widget/embedded/src/components/BlockchainsSection/BlockchainsSection.tsx, widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/NoResult/NoResult.tsx, widget/embedded/src/components/NotificationContent/NotificationContent.tsx, widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/components/TokenList/TokenList.tsx, widget/embedded/src/components/UpdateUrl.tsx, widget/embedded/src/components/WidgetEvents.tsx, widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.ts, widget/embedded/src/hooks/useSwapInput.ts, widget/embedded/src/hooks/useSyncStoresWithConfig.ts, widget/embedded/src/hooks/useWalletList.ts, widget/embedded/src/pages/Home.tsx, widget/embedded/src/pages/LiquiditySourcePage.tsx, widget/embedded/src/pages/SelectBlockchainPage.tsx, widget/embedded/src/pages/SelectSwapItemsPage.tsx, widget/embedded/src/pages/SettingsPage.tsx, widget/embedded/src/pages/SwapDetailsPage.tsx, widget/embedded/src/pages/WalletsPage.tsx, widget/embedded/src/store/AppStore.tsx, widget/embedded/src/store/app.ts
After merging [init config](https://github.com/rango-exchange/rango-client/pull/442), We've encountered some unexpexted behaviors like not updating the wallet state after connecting. The problem was after fetching the meta, the data inside context hasn't been updating.
The problem is we should call the store and return the App state in useAppStore hooks, if not, the component will not be re-rendered correctly and state has stale data inside it.
In Playground I tried to connect the wallet from `Connect Wallet` page then try to connect a wallet and go back to home.
=> fix(widget-v2): zustand store in context

widget/embedded/src/components/AppRouter.tsx, widget/embedded/src/components/UpdateUrl.tsx, widget/embedded/src/constants/searchParams.ts, widget/embedded/src/hooks/useForceAutoConnect.ts
A new feature has been added to the widget so that we can connect to the wallet by adding it as a autoConnect to the URL.
You can test this feature by running the widget and adding a autoConnect to the URL, the wallet should request a connection.
For example: http://localhost:3002/?autoConnect=braavos
=> feat(widget): handle wallet referrer in widget

wallets/provider-safe/src/helpers.ts, wallets/provider-walletconnect-2/package.json, yarn.lock
```
Server Error
TypeError: d is not a constructor  // d = SafeAppsSDK
```
=> fix(wallets): fix safe build issue in esm 

widget/embedded/src/QueueManager.tsx, widget/embedded/src/constants/index.ts, widget/embedded/src/containers/App/App.tsx, widget/embedded/src/containers/WidgetProvider/WidgetProvider.tsx, widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.ts, widget/embedded/src/hooks/useSwapInput.ts, widget/embedded/src/services/httpService.ts, widget/embedded/src/types/config.ts, widget/embedded/src/utils/configs.ts
In this task, we were supposed to support experimental features. These Items are set in the dapp & storage and in the widget, we read apiUrl or experimental best route from config. 
For testing, we can manually set config values for experimentalFeatures & apiUrl to change the request body of best route & apiUrl in our fetches.
=> feat(widget-v2): support experimental features

widget/embedded/src/components/NotificationContent/NotificationContent.tsx
A blank screen is displayed when clicking on a notification in the home page
Create a new swap and sign the transaction. After the transaction becomes successful, click on the notification in the home page.
=> fix(widget-v2): fix navigation in notification component

queue-manager/rango-preset/src/actions/executeTransaction.ts, queue-manager/rango-preset/src/helpers.ts, widget/embedded/src/containers/WidgetInfo/WidgetInfo.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.types.ts, widget/embedded/src/index.ts, widget/embedded/src/store/wallets.ts
In some steps we are getting the balance of the user, in this task we need to propagate the received data to dApp (like external wallets). It helps us to reduce network requests and make the widget a single source of truth for wallet balance.
these values are used in this PR https://github.com/rango-exchange/app/pull/12 and with linking it can be tested.
=> feat: add balances value to useWidget

widget/embedded/src/components/UpdateUrl.tsx, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/hooks/useSyncStoresWithConfig.ts
config values for tokens and blockchains doesn't affect the widget in memory router.
test widget with and without react router.
test widget with react router and search parameters for token and blockchain.
=> fix: fix widget configs in memory router

package.json, queue-manager/core/src/manager.ts, yarn.lock
It seems that our parcel serve is broken in next branch. I've fixed it by removing the yarn.lock and force updating it.
Also, it was needed to upgrade node version to v18 for some dependencies
=> fix: fix parcel serve issue

widget/embedded/src/components/TokenList/TokenList.helpers.ts, widget/embedded/src/components/TokenList/TokenList.tsx, widget/embedded/src/components/TokenList/TokenList.types.ts, widget/embedded/src/components/TokenList/index.ts, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/pages/Home.tsx, widget/embedded/src/pages/SelectSwapItemsPage.tsx, widget/embedded/src/store/quote.ts, widget/embedded/src/store/wallets.ts, widget/embedded/src/types/wallets.ts, widget/embedded/src/utils/wallets.ts
When a wallet is connected, navigation for choosing swap items, and the process of selecting blockchains experiences delays.
- improve getting the balance performance 
- running expensive logic only if the total balance changed
connect a wallet and change the selected blockchain
=> fix: fix performance issues on token selector in widget

queue-manager/rango-preset/src/actions/checkStatus.ts, wallets/provider-safe/src/evm-signer.ts, wallets/provider-safe/src/helpers.ts
The transaction URL during the 'checkStatus' step disappeared after refreshing when the wallet was either not connected or disconnected midway through the process.
The test can be conducted by restoring the removed condition and disconnecting the wallet in the middle of a bridge check-status.
=> fix: display transaction url after refreshing

widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.WalletState.tsx, widget/ui/src/components/Wallet/Wallet.types.ts
On Swap page, when we are showing the button for connecting the required wallet, if you click on connect wallet twice (when the wallet is on connecting state), it will crash.
We should disable the button, when we are connecting the wallet.
pass wallet-core state to wallet button
On Swap page, when we are showing the button for connecting the required wallet, if you click on connect wallet twice (when the wallet is on connecting state), It should not prompt any errors.
=> fix: fix wallet button state in swap details page

widget/embedded/src/components/TokenList/TokenList.tsx, widget/embedded/src/components/TokenList/TokenList.types.ts, widget/embedded/src/pages/SelectSwapItemsPage.tsx, widget/embedded/src/store/slices/data.ts, widget/embedded/src/types/config.ts, widget/embedded/src/utils/wallets.ts, widget/playground/src/components/MultiSelect/MultiSelect.tsx, widget/playground/src/components/MultiSelect/MultiSelect.types.ts, widget/playground/src/components/TokensPanel/TokensPanel.List.tsx, widget/playground/src/components/TokensPanel/TokensPanel.tsx, widget/playground/src/components/TokensPanel/TokensPanel.types.ts, widget/playground/src/containers/FunctionalLayout/FunctionalLayout.From.tsx, widget/playground/src/containers/FunctionalLayout/FunctionalLayout.To.tsx, widget/playground/src/containers/SupportedTokens/SupportedTokens.tsx, widget/playground/src/store/config.ts
We should have added the pinnedToken feature to the playground and changed its structure
You can test this feature through Playground in the Supported Tokens section
=> feat: implement pin tokens in From and To

widget/playground/src/components/ItemPicker/ItemPicker.styles.ts
After modifying the styles of the tooltip component, the default token style in the playground was affected. This pull request addresses the issue and ensures consistent styling.
=> fix: correct item picker style

wallets/provider-all/package.json, wallets/provider-all/src/index.ts, wallets/provider-default/package.json, wallets/provider-default/readme.md, wallets/provider-default/src/helpers.ts, wallets/provider-default/src/index.ts, wallets/provider-default/src/signer.ts, wallets/provider-default/tsconfig.json, wallets/shared/src/rango.ts, widget/embedded/src/hooks/useWalletList.ts
Many dApps show a default injected wallet, so users could connect to that even their wallet is not supported by the dApp explicitly (as almost all wallets implemented same api)
=> feat: add default injected wallet

widget/app/public/index.css, widget/app/src/App.tsx, widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/Layout/Layout.styles.ts, widget/embedded/src/components/Layout/Layout.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsCompleteModal.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.tsx, widget/embedded/src/components/WalletModal/WalletModal.tsx, widget/embedded/src/constants/index.ts, widget/embedded/src/containers/App/App.styles.ts, widget/embedded/src/utils/common.ts, widget/iframe/src/main.ts, widget/iframe/src/styles.ts, widget/iframe/tsconfig.json
After updating the widget to version 2, the i-frame version of the widget no longer functions correctly. Its styles need adjustment, and the dimensions of the i-frame must be updated, along with refining several styles.
The dimensions of the i-frame should change based on the widget layout dimensions. The background of the widget-app should be removed, and the widget should cover the entire i-frame.
First, we need to serve the widget-app in one place. You can use the 'serve' package for ease of use:
```
serve --cors -p 3002
```
In the main.ts file, we modify the source address of the i-frame from the widget-i-frame package to the address where the widget-app is served. We then build the widget-i-frame package.
We place the code exported from the playground for the i-frame …
=> fix: fix widget-iframe styles

signers/signer-starknet/src/signer.ts
We frequently faced this error: `Cannot read properties of undefined (reading 'execute')` in production when users are trying to sign starknet transactions.
=> hotfix: fix starknet signer problem

widget/playground/src/components/ExportConfigModal/ExportConfigModal.styles.tsx, widget/playground/src/components/ExportConfigModal/ExportConfigModal.tsx, widget/playground/src/components/SideNavigation/SideNavigation.Tabs.tsx, widget/playground/src/components/SideNavigation/SideNavigation.styles.ts, widget/playground/src/containers/StyleLayout/StyleLayout.Themes.tsx, widget/playground/src/containers/StyleLayout/StyleLayout.styles.ts, widget/ui/src/components/Button/Button.tsx, widget/ui/src/components/Button/Button.types.tsx
Implemented a smooth transition for tab-switching for both the LeftNavigation Tabs indicator and the background of the themes tab. 
Switching tabs in LeftNavigation and themes should have a smooth transition.
=> feat: add transition for tabs

wallets/core/src/types.ts, wallets/core/src/wallet.ts, wallets/provider-argentx/src/index.ts, wallets/provider-bitget/src/index.ts, wallets/provider-braavos/src/index.ts, wallets/provider-brave/src/index.ts, wallets/provider-coin98/src/index.ts, wallets/provider-coinbase/src/index.ts, wallets/provider-cosmostation/src/index.ts, wallets/provider-frontier/src/index.ts, wallets/provider-keplr/src/index.ts, wallets/provider-leap-cosmos/src/index.ts, wallets/provider-math-wallet/src/index.ts, wallets/provider-okx/src/index.ts, wallets/provider-phantom/src/index.ts, wallets/provider-safe/src/index.ts, wallets/provider-safepal/src/index.ts, wallets/provider-station/src/index.ts, wallets/provider-xdefi/src/index.ts, wallets/react/src/types.ts, wallets/shared/src/providers.ts, wallets/shared/src/rango.ts, widget/embedded/src/containers/Wallets/Wallets.tsx
This pull request resolves the issue where the 'accountChanged' event fires twice in wallets like Metamask when we change the accounts, causing duplicate server requests for walletDetails.
To reproduce (for example in https://widget.rango.exchange/) by switching MetaMask accounts, observe multiple server requests for balance and account information.
[Screencast](https://github.com/rango-exchange/rango-client/assets/123297941/ce9dc26f-cd9b-4b8d-82f9-b91d6582b611)
I added cleanup functions in both wallets/core and providers. I tested all wallets. For those without "off" events, I returned `void` during cleanup. The testing procedure ensured that changing the account triggers a single server request.
=> fix: walletDetails request is fired twice

widget/embedded/src/hooks/useSyncStoresWithConfig.ts, widget/embedded/src/index.ts, widget/embedded/src/store/slices/data.ts, widget/embedded/src/types/config.ts, widget/embedded/src/utils/configs.ts, widget/playground/src/components/MultiList/MultiList.styles.ts, widget/playground/src/components/MultiList/MultiList.tsx, widget/playground/src/components/MultiSelect/MultiSelect.tsx, widget/playground/src/components/MultiSelect/MultiSelect.types.ts, widget/playground/src/components/TokensPanel/TokensPanel.List.tsx, widget/playground/src/components/TokensPanel/TokensPanel.tsx, widget/playground/src/components/TokensPanel/TokensPanel.types.ts, widget/playground/src/containers/DefaultChainAndToken/DefaultChainAndToken.tsx, widget/playground/src/containers/SupportedTokens/SupportedTokens.tsx, widget/playground/src/store/config.ts, widget/playground/src/utils/configs.ts
Be able to exclude tokens from all or a single blockchain. exclude and include should works together at the same time.
In the supported tokens of the playground, you can specify whether it is excluded or included for the tokens of each blockchain.
=> feat: Update filter tokens interface in widget

widget/embedded/src/components/HeaderButtons/HeaderButtons.types.ts, widget/embedded/src/components/HeaderButtons/HomeButtons.tsx, widget/embedded/src/hooks/useSwapInput.ts
On the home page, if we have a quote and set the source and destination tokens to be the same, it disrupts the state, and the user can navigate to the "confirm-swap" page. Additionally, on the home page, when hovering over the "notifications" button and clicking on it, as long as the notification popover is open, the notification tooltip is visible.
Resetting the quote state when tokens are identical.
Removing the popover component from within the notification tooltip.
=> fix: reset the quote when the source token matches the destination token

widget/embedded/src/components/Slippage/Slippage.tsx, widget/embedded/src/components/SwapsGroup/SwapsGroup.tsx, widget/ui/src/components/SwapListItem/SwapListItem.types.ts, widget/ui/src/components/SwapListItem/SwapToken.tsx, widget/ui/src/components/Wallet/Wallet.styles.ts
Some minor bugs should be resolved.
=> fix: address some minor bugs in swapHistory & wallet page loading

widget/ui/src/components/SwapListItem/mock.ts
There was a bug in ui build related to the swap token data type.
=> fix: correct token data type in storybook

.github/workflows/crowdin.yml
Crowding is failing because it should be `rebase`d.
=> chore(ci): rebase pr for crowdin

.github/workflows/crowdin.yml, .github/workflows/publish.yml
After rebasing crowding branch, it causes run publish workflow recursively.
=> chore(ci): skip workflow on crowdin commit

widget/embedded/src/containers/App/App.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.types.ts, widget/embedded/src/hooks/useLanguage.ts, widget/embedded/src/store/slices/settings.ts, widget/playground/src/containers/StyleLayout/StyleLayout.General.tsx
When navigating to a new route, the language restores to the default state (En).
this issue was fixed by persistent language in the store.
=> fix: persist language in store

widget/app/src/App.tsx, widget/embedded/src/containers/WidgetProvider/WidgetProvider.tsx
This pull request addresses the issue where setting the apiKey in an iframe resulted in the creation of a transaction with the default apiKey instead of the apiKey provided in the configuration.
I tested this change using the provided template [here](https://docs.rango.exchange/widget-integration/quick-start#iframe-version). The `WIDGET_URL` was set to 3000, and the widget was run on port 3000. During testing, I monitored network requests to confirm that the correct apiKey was being sent from the configuration to the iframe.
=> fix: address apiKey config bug in iframe

widget/ui/src/components/RefreshProgressButton/RefreshProgressButton.styles.ts
The icon refresh styles didn't appear correctly on firefox.
The refresh icon should be tested on Firefox.
=> fix: correct refresh icon style on firefox

widget/playground/src/App.tsx, widget/playground/src/components/ExportConfigModal/CodeBlock.styles.tsx, widget/playground/src/components/ExportConfigModal/CodeBlock.tsx, widget/playground/src/components/ExportConfigModal/CodeBlock.types.tsx, widget/playground/src/components/ExportConfigModal/ExportConfigModal.tsx, widget/playground/src/components/MultiSelect/MultiSelect.styles.ts, widget/playground/src/components/MultiSelect/MultiSelect.tsx, widget/playground/src/components/MultiSelect/MultiSelect.types.ts, widget/playground/src/components/Slider/Slider.tsx, widget/playground/src/constants/index.ts, widget/playground/src/containers/DefaultChainAndToken/DefaultChainAndToken.tsx, widget/playground/src/containers/FunctionalLayout/FunctionalLayout.Liquidities.tsx, widget/playground/src/containers/StyleLayout/StyleLayout.styles.ts, widget/playground/src/containers/SupportedBlockchains/SupportedBlockchains.tsx, widget/playground/src/containers/SupportedTokens/SupportedTokens.tsx
Add animations and some improvements to Playground
=> fix: add animations and some improvements to playground

.github/workflows/checks.yaml, .github/workflows/deploy.yml, .github/workflows/publish.yml, docs/release.md, scripts/common/git.mjs, scripts/common/github.mjs, scripts/release/command.mjs
I changed the triggering of the publishing workflow.
And now both Branch **Main** and  **Next** will be triggered on **push** any commit. It is also will be triggered when a Pull Request has been merged.
**[skip ci]** is added for release commits that do not trigger the workflow on **next** or **prod** publish again.
For releasing production,  it tries to merge the **next** into **main** by **--no-ff** strategy, To make sure that a new commit is made And previous commits that may have `[skips ci]` Do not prevent workflow from triggering.
- Fix close PR issue: Workflow should not be run when closing the PR. Now by putting the trigger on the **push**, this problem is solved.
- Fix the workflow status of each commit: When the PR trigger was on **pull_request**, The status of …
=> fix: fix publish workflow status issue

widget/playground/src/utils/common.ts
The playground displays the Default wallet type. There is no need for it, so this PR removes it from the wallet list in playground settings.
=> chore: remove default wallet from playground

.vscode/settings.json, widget/embedded/src/components/Quote/Quote.styles.ts, widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/components/Quote/Quote.types.ts, widget/embedded/src/components/Quote/QuoteTrigger .tsx, widget/embedded/src/utils/quote.ts, widget/ui/src/components/Tooltip/Tooltip.styles.ts, widget/ui/src/components/Tooltip/Tooltip.tsx, widget/ui/src/components/Tooltip/Tooltip.types.ts, widget/ui/src/theme.ts
For long routes, we should show a shorter version and hide the rest in a button.
=> feat: for long routes, we should show a shorter version and hide the rest in a button.

wallets/provider-safe/src/helpers.ts
The Safe wallet team is attempting to evaluate the functionality of the Rango Dapp, but the auto-connect feature is not functioning. We need to adjust the Safe wallet configuration so that it can accept messages from their domain.
remove "allowedDomains" from the Safe wallet options to enable the wallet to accept messages from any domain.
Link wallet packages within the Rango Dapp and test the Rango Dapp in the Safe custom apps.
=> chore: accept safe wallet messages from all domains

.eslintrc.json, .lintstagedrc.mjs, package.json
Typescript parser needs to point a `tsconfig`, by passing `project: true` it uses nearest `tsconifg.json` but the problem is we don't have any `tsconfig.json` in root. I fixed it by ignoring root files using `projectFolderIgnoreList` option.
More datails: 
https://typescript-eslint.io/packages/parser/#project
Fixes RNG-1221
Try to change some files in root and then run the linter on the file using:
```
npx eslint global-wallets-env.d.ts --ignore-path ./.eslintignore
```
And also do some changes that breaks our eslint rules then add them to your git's stage then run following command:
```
npx lint-staged  
```
=> chore: fix linter for monorepo root files

widget/ui/.storybook/preview.tsx, widget/ui/src/components/Alert/Alert.styles.ts, widget/ui/src/components/Toast/Toast.Provider.tsx, widget/ui/src/components/Toast/Toast.helpers.ts, widget/ui/src/components/Toast/Toast.stories.tsx, widget/ui/src/components/Toast/Toast.styles.ts, widget/ui/src/components/Toast/Toast.tsx, widget/ui/src/components/Toast/Toast.types.ts, widget/ui/src/components/Toast/index.ts, widget/ui/src/components/index.ts
- Implemented  `Toast` component.
Toast component has not been used in widget (embedded) yet, and for testing its Provider should be used somewhere in widget. but for testing in dapp, it can be tested by linking this PR with this PR: https://github.com/rango-exchange/app/pull/45.
if you don't want to test in dapp and just test in widget, first you need to wrap one of higher components in widget with `ToastProvider`  like this:
```
<ToastProvider
anchorOrigin={{
vertical: 'top',
horizontal: 'right',
}}><Layout /></ToastProvider>
```
and then use addToast function inside it:
```
addToast({
title:'Hi',
type: 'success',
});
```
=> feat: implement toast

widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.WalletState.tsx, widget/embedded/src/hooks/useWalletList.ts, widget/embedded/src/pages/WalletsPage.tsx, widget/embedded/src/utils/wallets.ts
When the Wallet state is **connecting** and leaves the page or component, we disconnect all connecting statuses in the clean-up component.
And if the modal connecting wallet is closed, we disconnect the wallet again.
This issue has been fixed in 3 different places:
-  WalletPage
- ConfirmWalletsModal
- SwapDetail
After clicking to connect the wallet, do not close the main window of the wallet,
so that it remains in the connecting mode.
Then you can click on the back of the browser or close the conecting modal.
After you return to the previous page, Wallet should be disconnected.
=> fix: fix connecting wallet issue

widget/ui/src/components/Modal/Modal.tsx, widget/ui/src/components/Modal/Modal.types.ts
Added a transition duration prop to modal component to have a access to change the transition of modal.
=> feat: add transitionDuration prop to modal

widget/embedded/src/components/Layout/Layout.styles.ts, widget/embedded/src/components/Layout/Layout.tsx, widget/embedded/src/constants/searchParams.ts, widget/embedded/src/hooks/useIframe/index.ts, widget/embedded/src/hooks/useIframe/useIframe.helpers.ts, widget/embedded/src/hooks/useIframe/useIframe.ts, widget/embedded/src/hooks/useIframe/useIframe.types.ts, widget/embedded/src/hooks/useSyncUrlAndStore/useSyncUrlAndStore.ts, widget/embedded/src/store/slices/config.ts, widget/iframe/src/main.ts, widget/iframe/src/styles.ts, widget/iframe/src/utils.ts
We've a new feature for iframes to be able to get the swap box/widget height. There are some solutions to solve this:
1. Adding a new config to detect iframe
2. Using message passing to set some inital values (widget url is need to send messages between origins)
3. Using query param to set the initial value
The first one will pollute our public API for widget, so this is last thing I wanted. I tried the second approach but it has some issues regarding we couldn't detect when dom is ready in embedded page in iframe. I chose the last one, I added a `clientUrl` to be set from our iframe script, it will be used to send message between origins.
I also introduced a new standard way for our message passing. Another change is adding a feature management to our iframe script so user can activate …
=> feat: add dynamicHeight to iframe

widget/embedded/src/components/CustomCollapsible/CustomCollapsible.tsx, widget/embedded/src/components/Quote/Quote.tsx
In this pull request, we eliminated the auto-scroll feature present in collapsible components such as the quote and fee modal, which used to trigger the scrolling of the entire app utilizing the widget. Our plan is to implement a more robust solution for this behavior in the future.
=> fix: remove auto scroll behavior from collapsible components

.github/workflows/checks.yaml, .github/workflows/crowdin.yml, .github/workflows/release.yml, docs/release.md, scripts/common/constants.mjs, scripts/common/utils.mjs, scripts/post-release/command.mjs, scripts/post-release/tag.mjs
A new workflow named **Production Release**  has been added, which takes the latest translation changes on the **next** branch and then automatically performs the production release.
Testing scenarios:
Making a pull request on next then merge the PR, After merging PR into next, You can run yarn **production release** workflow manually, it should pull crowdin change on **next** branch and then it will automatically published.
=> feat: add production release workflow

widget/embedded/src/components/HistoryGroupedList/HistoryGroupedList.tsx
When refreshing the widget on the history page, there is a brief flickering of the list of swaps during the initial rendering.
https://github.com/petyosi/react-virtuoso/issues/734
https://github.com/petyosi/react-virtuoso/issues/734#issuecomment-1219926838
Update: 
Due to the limitations of the react-virtuoso package in resolving the issue and its primary function of calculating dimensions for lists, coupled with the fact that the issue is more apparent in development than in a production build, we have chosen not to make any modifications at this time.
=> fix: fix virtual list flicker in history page

widget/embedded/src/components/Layout/Layout.tsx, widget/embedded/src/containers/Widget/Widget.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.tsx, widget/embedded/src/libs/tabManager/tabManager.ts, widget/embedded/src/libs/tabManager/tabManager.types.ts, widget/embedded/src/store/ui.ts
We have recently introduced a feature that allows for having a single active tab in the widget, but it has been causing issues with the Next.js build. This pull request addresses the issue by fixing the problem and ensuring that the document object is accessed and relevant event listeners are attached only after the widget has been mounted on the DOM.
=> hotfix: fix tab manager error in Next.js

wallets/shared/package.json
We missed adding `ethers` to `shared` package.
=> fix: add ethers to shared package

widget/embedded/package.json
Adding `ethers` as dependency to fix `pnpm` issue.
=> fix: add ethers dependency to embedded

widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/hooks/useWalletList.ts, widget/embedded/src/pages/WalletsPage.tsx, widget/embedded/src/utils/wallets.ts
On the wallet page and confirm swap, if we click on a wallet logo, it remains in the connecting mode, when we close the connecting modal, the wallet should change from connecting to disconnecting mode.
After clicking to connect the wallet, do not close the main window of the wallet,
so that it remains in the connecting mode.
Then you can close the conecting modal.
After close connecting modal, Wallet should be disconnected.
=> fix: reset connecting state on close wallet modal

.github/workflows/checks.yaml, .github/workflows/crowdin.yml, .github/workflows/publish.yml, .github/workflows/release.yml, scripts/common/errors.mjs, scripts/crowdin/command.mjs, scripts/crowdin/constants.mjs, scripts/crowdin/pretranslate.mjs, scripts/crowdin/utils.mjs
crowdin was removed from the publish and check workflows.
From now on, we only have crowdin in the release process
So that for each release:
- First, it extracts the new strings
- Then it pushes new strings to crowdin
- Then the pre-translate script will be called
- Then it downloads the translations for different languages, and opens a PR and merges all new translations to the **Next** branch.
And finally, it continues the release process
To test, you can first take some PRs from **Next** Branch and change the string in some files and merge them into **Next** Branch.
Finally, call the release workflow manually,
In this case, the new strings that are on the next branch must be uploaded to crowdin, pre-translated and new translations must be downloaded for each language and merged in the …
=> feat: update crowdin workflow and add pretranslate step

lingui.config.ts, translations/pt.po, widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/constants/languages.ts, widget/embedded/src/pages/SettingsPage.tsx, widget/playground/src/constants/languages.ts, widget/ui/src/components/Flags/Portuguese.tsx, widget/ui/src/components/Flags/index.ts, widget/ui/src/components/I18nManager/I18nManager.tsx
- add Portuguese language to setting section
- add Portuguese language to playground list for default language
If the pt.po file with crowdin translations has not been prepared yet, you can use the crowdin test account in your fork or change the pt.po file manually for convenience and start yarn again for compile new translation.
=> feat: add Portuguese language to widget

queue-manager/rango-preset/src/actions/executeTransaction.ts, queue-manager/rango-preset/src/constants.ts, wallets/shared/src/providers.ts, widget/embedded/src/QueueManager.tsx, widget/embedded/src/containers/Wallets/Wallets.tsx
Some displayed messages during the swap process are incorrect.
Initiate a swap on the Osmosis network, proceed to the sign transaction pop-up, and without signing the transaction, refresh the page. After the page reloads, attempt to connect the necessary wallet on the swap-details page.
=> fix: fix some swap messages in widget-embedded

.github/actions/prepare/action.yml
We are forcing using yarn, so we should make sure we don't run any command using npm.
=> chore: remove npm whoiam from prepare action

package.json, scripts/deploy/utils.mjs, yarn.lock
Using npx for vercel deployment to keep local deps clean.
=> chore: remove vercel from local deps and use npx whenever we need

widget/embedded/src/components/Layout/Layout.styles.ts, widget/embedded/src/components/Layout/Layout.tsx, widget/embedded/src/components/common/ActivateTabAlert/ActivateTabAlert.tsx, widget/embedded/src/pages/Home.tsx
Update active tab warning position
To see the warning displayed by the widget, open two tabs.
=> feat: update active tab warning position

wallets/core/src/types.ts, wallets/core/src/wallet.ts, wallets/provider-walletconnect-2/package.json, wallets/provider-walletconnect-2/src/helpers.ts, wallets/provider-walletconnect-2/src/index.ts, wallets/provider-walletconnect-2/src/session.ts, wallets/provider-walletconnect-2/src/signers/evm.ts, wallets/provider-walletconnect-2/src/types.ts, wallets/react/src/types.ts, wallets/shared/src/rango.ts, yarn.lock
Currently we have problem in initial connection to some wallets as we forced some required methods in the session proposal request. We could just leave required namespace as empty and pass everything we need as the optional namespace. So, it should work even if the wallet doesn't support some specific chains/methods. 
When we submit a session proposal, we receive the final accepted namespace in session response. So we could rely on that afterward. 
For some exceptional wallets e.g. trust wallet and 1inch mobile wallet, they are returning wrong namespace methods in response of the session, so we could just ignore their authorised namespace methods. For example, trust wallet is returning `wallet_switchEthereumChain` in the response but it doesn't support it.
Also for the matter of switch …
=> fix: fix wallet connect bugs in switch network and namespaces

widget/embedded/src/components/NoResult/NoResult.helpers.ts, widget/embedded/src/components/NoResult/NoResult.styles.ts, widget/embedded/src/components/NoResult/NoResult.tsx, widget/embedded/src/components/NoResult/NoResult.types.ts, widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/components/Quote/Quote.types.ts, widget/embedded/src/components/Quotes/Quotes.tsx, widget/embedded/src/components/Quotes/Quotes.types.ts, widget/embedded/src/containers/ExpandedQuotes/ExpandedQuotes.styles.ts, widget/embedded/src/containers/ExpandedQuotes/ExpandedQuotes.tsx, widget/embedded/src/containers/QuoteInfo/QuoteInfo.tsx, widget/embedded/src/containers/QuoteInfo/QuoteInfo.types.ts, widget/embedded/src/pages/Home.tsx, widget/embedded/src/types/config.ts, widget/embedded/src/utils/configs.ts, widget/playground/src/constants/variants.ts, widget/ui/src/components/Alert/Alert.tsx, widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.styles.ts, widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.tsx
The full expanded variant for the route was added to the widget  We should make sure every part works together correctly:
1. full expanded quote component
2. filter and refresh 
3. errors flow 
4. playground: add a new variant to the playground
You can change **config.variant** to test all variants of the route 
for example:
```
config = {
apiKey: '',
variant: 'full-expanded',
walletConnectProjectId: WC_PROJECT_ID,
};
```
=> feat: add full expanded variant to widget

widget/embedded/src/store/slices/settings.ts
When a feature is hidden, the default value should be from config.
hide a feature and give it value from config
=> fix: correct default values of hidden features

widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.helpers.ts, widget/embedded/src/pages/Home.tsx
Displaying error modals for routes is not accurate in expanded mode. Even when changing the selected route, we continue to show the error modal, even if that route doesn't have a similar error. 
Additionally, the alert for the bridge limit error should remain without any associated action; the action button related to it needs to be removed . 
=> fix: fix bugs in displaying quote error modals

widget/app/public/index.css, widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/components/Quotes/Quotes.tsx, widget/embedded/src/containers/App/App.styles.ts, widget/embedded/src/containers/ExpandedQuotes/ExpandedQuotes.styles.ts, widget/embedded/src/pages/Home.tsx, widget/playground/src/containers/BoundaryGuideContainer/BoundaryGuideContainer.styles.ts, widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.styles.ts, widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.tsx, widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.types.ts
=> fix: correct height of widget

widget/embedded/src/containers/Settings/Lists.tsx, widget/embedded/src/hooks/useSwapInput.ts, widget/embedded/src/pages/LiquiditySourcePage.tsx, widget/embedded/src/store/slices/data.ts, widget/embedded/src/types/config.ts, widget/embedded/src/utils/swap.ts
Add enabling centralized swappers to config to pass to get meta & get route api params.
by passing `enableCentralizedSwappers` to config & checking the body of meta & qoute api call params
=> feat: add enabling centralized swappers to config

widget/embedded/src/components/QuoteSkeleton/QuoteSkeleton.styles.ts, widget/embedded/src/components/QuoteSkeleton/QuoteSkeleton.tsx, widget/embedded/src/components/QuoteSkeleton/QuoteSummarySkeleton.styles.ts, widget/embedded/src/components/QuoteSkeleton/QuoteSummarySkeleton.tsx, widget/embedded/src/components/QuoteSkeleton/StepSkeleton.styles.ts, widget/embedded/src/components/QuoteSkeleton/StepSkeleton.tsx, widget/embedded/src/components/QuoteWarningsAndErrors/HighValueLossWarningModal.tsx, widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.helpers.ts, widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.styles.ts, widget/embedded/src/components/Quotes/Quotes.tsx, widget/embedded/src/constants/errors.ts, widget/embedded/src/containers/Inputs/Inputs.tsx, widget/embedded/src/pages/ConfirmSwapPage.tsx, widget/embedded/src/utils/swap.ts
some minor improvements on the widget
=> fix: apply minor improvements to the widget

widget/embedded/src/components/SwapDetails/SwapDetails.tsx
There was an issue in dapp that we didn't close complete modals when clicked on notification items.
Linking by alpha branch of dapp
=> fix: close completeModal when requestId is changed

widget/embedded/src/containers/Settings/Lists.tsx, widget/embedded/src/pages/LanguagePage.tsx
In this PR, we are navigating to widget setting when user select a new language. (to avoid ux issue for re-rendering the widget and scrolling to the top)
By changing selected language in widget settings.
=> fix: navigate to setting page when lanaguage changed

widget/embedded/src/hooks/useTheme.ts
Removing a redundant param to avoid overriding theme setting
=> fix: default theme shouldn't be override on what user has set

widget/embedded/src/containers/Settings/Lists.tsx
Removed redundant punctuation from settings page
=> fix: remove redundant punctuation from settings page

widget/embedded/src/store/slices/settings.ts
When the previous setting of widget mode is dark or light, and single theme is true, the theme didn't change.
=> fix: get theme from config when singleTheme is true

widget/embedded/global-env.d.ts, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/tsconfig.json
attach `config` passed to widget to window
e.g.:
window.__rango.config
The config is available in the console.
=> feat: attach config passed to widget to window

widget/embedded/src/components/Layout/Layout.tsx, widget/embedded/src/components/RefreshModal/RefreshModal.styles.ts, widget/embedded/src/components/RefreshModal/RefreshModal.tsx, widget/embedded/src/components/RefreshModal/RefreshModal.types.ts, widget/embedded/src/components/RefreshModal/index.ts
When meta hasn't load correctly (Network condition, or error), Show a modal with page reload option
Put the app in a situation where the meta doesn't load correctly.
=> feat: show a modal with page reload

wallets/provider-argentx/src/index.ts, wallets/provider-braavos/src/index.ts, wallets/provider-brave/src/index.ts, wallets/provider-clover/src/index.ts, wallets/provider-coin98/src/index.ts, wallets/provider-coinbase/src/index.ts, wallets/provider-cosmostation/src/index.ts, wallets/provider-exodus/src/index.ts, wallets/provider-frontier/src/index.ts, wallets/provider-okx/src/index.ts, wallets/provider-phantom/src/index.ts, wallets/provider-xdefi/src/index.ts, wallets/shared/src/providers.ts
When a user tries to connect to a particular wallet and it gets overridden by another wallet, and the instance lacks the `on` or `off` methods, it results in an error or app malfunction: 
We resolve this by conditionally invoking `on` and `off` methods.
You can test this by enabling both the 'Core' and 'Metamask' wallets, then attempting to connect to the 'Metamask' wallet. The overridden wallet, 'Core' in this scenario, should connect successfully.
=> fix: fix the connection problem that happens when another wallet takes over the requested one

wallets/provider-tron-link/src/index.ts
Resolved following error when connecting to tron-link wallet: 
"Error: Cannot read properties of undefined (reading 'toString')"
Fixes # RF-1378
You can test this by connecting to Tron Link.
=> fix: fix tron-link wallet connecting error

.github/workflows/checks.yaml, package.json, scripts/common/errors.mjs, scripts/common/github.mjs, scripts/deploy/command.mjs, scripts/deploy/config.mjs, scripts/deploy/utils.mjs, yarn.lock
To show the deployment preview link for each PR, a step has been added in the check workflow that calls the deploy script.
In the deployment preview step, for any project that we want a preview link in the PR, we just need to set the environment ENABLE_PREVIEW_DEPLOY to true and add the vercel ID of the projects we want in the env section.
We also need to define a new job in the check workflow for each project for which we want a preview link, and add the environment related to the preview link to it.
In the deployment script, if ENABLE_PREVIEW_DEPLOY is equal to true, the deployment process is performed for the projects that are in the check workflow, the vercel project ID is located in it, and it is deployed in vercel, and the preview link is extracted and placed in the Github output, …
=> feat: add preview deployment to pr

widget/embedded/src/components/TokenList/TokenList.tsx
Sometimes, the infinite loader in the token selector, which loads more pages when the list reaches its end, doesn't work.
This bug occurs when the widget fetches wallet balances and you scroll through a long list in the token selector. Or when you scroll through a long token list, causing it to load at least one more page, and switch between browser tabs, with the current tab becoming hidden, then returning to the same tab after.
=> fix: fix token selector infinite loader

widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.ts
We should fix passing validations parameters in create transaction step:
```validations: {balance: false, fee: false}```
if user proceed anyway => pass both `false`
otherwise => pass both `true`
=> fix: make sure to correctly pass validation parameters when setting up a new swap

widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.ts, widget/embedded/src/hooks/useFetch.ts
Added an auto-retry for the confirmation step if it fails; it will only be called once.
It can be tested by disabling the network during the confirmation step
=> feat: add auto retry for fetching confirm swap

widget/embedded/src/hooks/useSyncUrlAndStore/useSyncUrlAndStore.ts, widget/embedded/tsconfig.json
We should keep "utm_" params in first load.
set search params including utm_
=> chore: keep utm search params in url

signers/signer-solana/src/utils/simulate.ts
Added support for detecting "insufficient funds" and "slippage error" for solana signer.
Fixes # RF-1475
=> feat: clean solana signer simulation errors

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWallets.helpers.ts, widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/pages/ConfirmSwapPage.tsx, widget/embedded/src/utils/swap.ts, widget/embedded/src/utils/wallets.ts
If a user connects a wallet different from the required type for the swap process and attempts to confirm the wallet, no wallet is selected in the confirmation modal. However, if the user inputs a valid custom address, the confirm button becomes enabled, allowing the user to proceed with the swap. In this scenario, no selected wallet is transmitted to the server, potentially resulting in the failure of the transaction creation process: 
First, connect only the `Keplr` wallet. Then, attempt a swap on an EVM route. In the confirm wallet modal, enter a valid custom address.
=> fix: disable the confirm wallet button if all required wallets are not selected

wallets/provider-all/package.json, wallets/provider-all/src/helpers.ts, wallets/provider-all/src/index.ts, wallets/provider-walletconnect-2/src/index.ts, widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/HeaderButtons/WalletButton.tsx, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/hooks/useWalletList.ts, widget/embedded/src/hooks/useWalletProviders.ts, widget/embedded/src/pages/WalletsPage.tsx, widget/embedded/src/utils/providers.ts, widget/playground/src/App.tsx
Implemented throwing error if WalletConnect is not excluded and WC_PROJECT_ID have not passed to provider-all.
Fixes # 1464
Tested it by excluding and including wallet-connect in widget wallets list and also adding and removing WC_PROJECT_ID.
=> feat: improve wallet connect variables check

widget/embedded/src/utils/wallets.ts
Occasionally, the server may provide a token symbol or token address with differences in capitalization between the ‍`Bests` response and the `Meta` response. 
These changes enhances the confidence level when checking tokens against each other
=> chore: verify token equality with greater assurance

widget/embedded/src/hooks/useSwapInput.ts, widget/embedded/src/hooks/useSyncStoresWithConfig.ts, widget/embedded/src/pages/ConfirmSwapPage.tsx, widget/embedded/src/pages/Routes.tsx
When we move from the routes page to the settings page and then return to the routes page, the fetching of quotes doesn't activate. 
The debouncing of the quotes request should only occur when there's a change in the input amount.
If the parameters for the quote are altered in the widget configuration (such as in the playground), the widget shouldn't be left in a broken state. This issue currently occurs on the `confirm swap` page and `routes` page. To address this, we can reset the quote state and redirect the user to the home page.
You can disable certain swappers or tweak the slippage, ensuring they're properly applied to the quotes request. 
After setting all the quotes parameters. Navigate from the home page to other pages. The quotes request should be triggered without any debounce.
=> fix: fix bugs in fetching quotes

signers/signer-solana/src/config.ts, signers/signer-solana/src/index.ts, signers/signer-solana/src/utils/helpers.ts, widget/embedded/package.json, widget/embedded/src/containers/WidgetProvider/WidgetProvider.tsx, widget/embedded/src/types/config.ts
Added custom solana rpc in signer config to widget config.
Fixes # RF-1504
Tested it by adding the below object to widget config:
```
signerConfig: { customSolanaRPC: 'customSolanaRPC' }
```
=> feat: add custom solana rpc url to config

.eslintrc.json, queue-manager/rango-preset/src/helpers.ts, signers/signer-evm/src/signer.ts, yarn.lock
For EVM transaction v2, the `gasPrice` should be omitted, and only the `maxFeePerGas` and `maxPriorityFeePerGas` should be provided to the provider for signing the transaction.
=> fix: exclude the gas price from evm transaction specifications in version 2

queue-manager/rango-preset/src/helpers.ts, signers/signer-evm/src/signer.ts, signers/signer-evm/src/types.ts
- In this PR, I've disabled unhandled errors in confirm transaction as they could be false positive.
- I've also commented one of the metamask errors to check something in production.
- Avoid sending trace of rpc errors to api when user reject the transactions.
=> hotfix: ignore confirm transaction unknown errors and proceed with check status

widget/embedded/src/components/HeaderButtons/HeaderButtons.tsx, widget/embedded/src/components/HeaderButtons/NotificationsBadge.tsx, widget/embedded/src/components/NotificationContent/NotificationContent.styles.ts, widget/embedded/src/components/NotificationContent/NotificationContent.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.tsx, widget/embedded/src/hooks/useBootstrap/useBootstrap.ts, widget/embedded/src/hooks/useSyncNotifications/index.ts, widget/embedded/src/hooks/useSyncNotifications/useSyncNotifications.ts, widget/embedded/src/store/notification.ts, widget/embedded/src/types/notification.ts, widget/embedded/src/utils/swap.ts
Sometimes, browsers may delete `indexedDB` data, causing notifications and swaps to become out of sync. As a result, clicking on notifications could lead users to empty pages because the related swaps no longer exist. These notifications then remain unread indefinitely. This pull request tackles this problem by addressing the issue and removing unnecessary notifications from the user's local storage. Additionally, it introduces a button for clearing all notifications.
https://developer.mozilla.org/en-US/docs/Web/API/Storage_API/Storage_quotas_and_eviction_criteria
Initiate a swap.
Use Chrome `DevTools` to clear the `indexedDB` database for swaps.
After refreshing the page, no notifications should remain.
If a swap has been completed (whether successful or failed) and the user has read the …
=> fix: sync notifications with persisted swaps

wallets/provider-ledger/src/index.ts, widget/embedded/src/hooks/useWalletList.ts
Shouldn't show Ledger in mobile view.
The ledger was causing problems for the Injected wallet
NOTE: Injected wallet for when we don't support an evm wallet and the user wants to connect with that wallet
Test on mobile display
For instance, you could try removing Metamask from the provider all and connecting to Metamask using the injected wallet to test the injected wallet.
=> fix: excluding ledger on mobile

widget/embedded/src/containers/WidgetProvider/WidgetProvider.tsx
Resolved initConfig minor bug which was leading to this error message in console:
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
=> fix: fix init config minor bug

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/ConfirmWalletsModal/WalletList.type.ts, widget/embedded/src/store/wallets.ts
Sometimes, connected wallets fail to be automatically selected in the confirm wallets modal.
Navigate to the confirm wallets modal and attempt to connect multiple wallets for a specific blockchain request. The latest connected wallet should be automatically chosen. Additionally, you should be able to switch between your selected wallets for a blockchain seamlessly.
This feature should function seamlessly with external wallets. To verify, enable external wallets in the widget playground and select multiple options like `MetaMask` and `Coinbase`. Next, navigate to the confirm wallets modal within the widget. Changes in the connection status of `MetaMask` wallet should reflect in the selected wallet within the confirm wallet modal.
=> fix: fix the automatic selection of the connected wallets in the confirm wallets modal

scripts/analyze-bundle/compare.mjs
The bundle analyze script throws an error when attempting to create a report after a new package is added to our repository.
=> chore: fix the analyze bundle script when a new package is added

widget/embedded/src/components/Layout/Layout.styles.ts, widget/embedded/src/hooks/useTheme.ts, widget/embedded/src/types/config.ts, widget/ui/src/theme.ts
For one of our users, we need to let them to hide the shadow around swap box. We don't have any specific way to override some styles directly so I solved it using `theme`. I'm not a fan of aliasing theme tokens (e.g. `mainContainer` that I've used ) but we didn't define `shadows` in our design system so they are hardcoded values right now. In our next iteration on design system we can rethink this part too. So I think it's the easiest way to achieve the user to hide the shadow. 
you need to pass this object as config:
```typescript
{
theme: {
shadows: {
mainContainer: '15px 15px 15px 0px rgba(0, 0, 0, 1)',
},
},
}
```
=> feat: adding 'shadows' to widget config for theme

widget/embedded/src/store/slices/settings.ts, widget/embedded/src/types/config.ts, widget/playground/src/App.tsx
Source of truth of the values should be config object in Playground, but if any changes happens inside the widget, it has more priority than config. We need to reset all the widget values in Playground on reload to make sure configs will be applied.
Note: It seemed that the problem was from Zustand's persistor, but the problem was that the setting wasn't updated by the config
Change the font in the playground first, then the widget. After changing the font once more in the playground, the widget's font should also change.
=> feat: make update settings optional to make it enable in playground

wallets/shared/src/rango.ts
When the `XDefi` wallet is not connected, it does not appear in the confirm wallets modal for the `Kujira` network. however, it appears after connecting
=> fix: fix the bug where xdefi is not displayed for experimental networks

widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/hooks/useWalletList.ts, widget/embedded/src/pages/WalletsPage.tsx, widget/embedded/src/utils/common.ts, widget/playground/src/App.tsx, widget/playground/src/components/MultiSelect/MultiSelect.styles.ts, widget/playground/src/components/Slider/Slider.tsx, widget/playground/src/components/Slider/Slider.types.ts, widget/playground/src/containers/FunctionalLayout/FunctionalLayout.Wallets.tsx, widget/playground/src/containers/StyleLayout/StyleLayout.General.tsx, widget/playground/src/store/config.ts, widget/playground/src/utils/export.ts
Fix walletConnectProjectId:
Don't insert 'walletConnectProjectId' in exported code if wallet-connect is excludedCurrently if the user exclude 'wallet-connect' in the list of wallets, we insert walletConnectProjectId in the exported code anyway. It should be removed if 'wallet-connect' is excluded.
Fix external wallets and supported wallets mismatch:
Reproduce
- Enable external wallet option
- Click on supported wallets (metamask is selected by default), Click on Select All and then Confirm.
- Click on export code button, it eliminated wallets and only keeps externalWallets: true.
Possible solution:
When external wallets has been enabled, we can disable Supported Wallets input to stop user from doing incorrect behaviour.
fix Enable Multi Wallets Simultaneously
Reproduce:
- Disable and …
=>  fix: some bugs in playground

signers/signer-solana/src/utils/main.ts, signers/signer-solana/src/utils/simulate.ts
Improved some Solana simulation errors:
1. AccountNotFound error changed to "Fee payer of transaction is an unknown account"
2. SBF program panicked changed to "Program failed to complete"
3. Th error message related to the third error in "@solana-web3.js" was "Custom program error". Considering that it is similar to the current error and it is not human friendly either, I didin't change it.
Fixes # 1513
1. create a solana transaction with a new solana account. (no balance and previous transactions)
2. create transaction from AVAX.SOLANA to USDT.SOLANA and sign it with an account with no balance.
2. create transaction from USDC.SOLANA to ATOM.Cosmos and sign it with an account with no balance.
=> feat: improve solana simulation failed errors

widget/embedded/src/components/NotificationContent/NotificationContent.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.types.ts, widget/embedded/src/store/notification.ts, widget/embedded/src/utils/meta.ts, widget/ui/src/containers/Notifications/NotificationNotFound.tsx, widget/ui/src/containers/Notifications/Notifications.styles.ts, widget/ui/src/containers/Notifications/Notifications.tsx, widget/ui/src/containers/Notifications/Notifications.types.ts, widget/ui/src/containers/Notifications/index.ts, widget/ui/src/containers/index.ts
Moving the notifications components to the UI package for use in the `widget-embedded` and `Dapp`. Display all notifications without limitations; it can be scrollable.
We can add properties to the notifications store to save and persist token and blockchain images, removing the utility functions for finding these images. However, this would require writing a migration and syncing older versions of the notifications store, potentially adding unnecessary complexity at this time.
=> feat: display all notifications in the notification popover

signers/signer-evm/src/signer.ts, wallets/provider-walletconnect-2/src/signers/evm.ts
We are facing `Unknown method(s) requested` error in wallet connect (using trust wallet) for some routes.
I've fixed the problem based on [this suggestion](https://github.com/WalletConnect/web3modal/issues/1082#issuecomment-1637793242) and added a default `0x` for the data field.
You could test this route before and after this change: (using trust wallet + wallet connect)
`0.1000 x BSC.BNB →[SWFT]→ ? ETH.ETH`
You need to enable centralized swappers to get this route.
=> fix: fix tx data for evm signer when transferring native token

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx
The custom destination was disabled as its value was altered in the widget and it had an undefined value in the playground.
So we don't display the custom destination in the playground by mistake.
Test in playground
=> fix: state of custom destination in playground

widget/embedded/src/store/slices/settings.ts, widget/embedded/src/types/config.ts, widget/playground/src/App.tsx
Two fields in the config were merged together since they served the same purpose.
=> chore: move autoUpdateSettings config to __UNSTABLE_OR_INTERNAL__

widget/embedded/src/containers/Inputs/Inputs.tsx, widget/embedded/src/store/quote.ts
solved two issues:
1. Incorrect updating of the input amount occurs when the source token is eliminated.
2. The dollar value at the destination is not updated accurately when tokens are removed.
The issue was that the values weren't updated appropriately when the tokens were removed.
In order to improve display, I added a condition to the inputs component that states that values will be presented correctly in the event that the token is removed or the USD value is null.
It is preferable to take the test on the playground:
1. First, indicate the token and input's default values.
2. Navigate to the token selection page. Choose all options without choosing a token.
3. Return to the home screen.
In this instance, the USD values ought to be shown appropriately.
=> fix: bug in updating input & output amount

widget/playground/src/store/config.ts
Persisted external wallets in storage.
Fixes # 1627
You can test this by checking/unchecking external wallets in playground and refreshing the page to see if it persists.
=> fix: persist external wallets in storage

tsconfig.base.json, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/services/cacheService.ts, widget/embedded/src/store/slices/config.ts, widget/embedded/src/store/slices/data.test.ts, widget/embedded/src/store/slices/data.ts, widget/embedded/src/store/utils/data.test.ts, widget/embedded/src/store/utils/data.ts, widget/embedded/src/store/utils/index.ts, widget/embedded/src/test-utils/fixtures.ts, widget/embedded/src/types/wallets.ts
If a token is excluded from a blockchain that hosts numerous tokens, such as Ethereum, it leads to a decline in the widget's performance.
You can verify this using the playground. In either the 'from' or 'to' section, navigate to the Ethereum tokens subsection, exclude one token, and confirm the adjustments. Afterwards, attempt to interact with the widget by transitioning from the home page to the tokens page and searching for a token.
=> fix: improve widget performance

widget/embedded/src/store/notification.ts, widget/embedded/src/types/notification.ts
Fixed sort logic of notifications so they get displayed sorted based on transactionCreationTime.
Fixes # 1662
Tested this by creating a transaction. So when that tx is in the check status state, if I get a new notification, it will appear on top of the old check status notification in notifications list.
=> fix: fix sort logic of notifications

widget/embedded/src/index.ts, widget/embedded/src/pages/Home.tsx, widget/embedded/src/types/event.ts, widget/embedded/src/utils/events.ts
We need to detect when a user clicks on the "Connect Wallet" button at the bottom of the widget's homepage, prevent navigation to the wallet connection page, and allow for adding a custom callback from outside the widget.
```ts
useEffect(() => {
const handleEvent = (event: UiEventData) => {
if (event.type === UiEventTypes.CLICK_CONNECT_WALLET) {
console.log('ui events', event);
event.payload.preventDefault();
}
};
eventEmitter.on(WidgetEvents.UiEvent, handleEvent);
return () => eventEmitter.off(MainEvents.UiEvent, handleEvent);
}, [eventEmitter]);
```
=> feat: add a new event for the connect wallet button click

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWallets.styles.ts, widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/components/CustomDestination/CustomDestination.styles.ts, widget/embedded/src/components/CustomDestination/CustomDestination.tsx, widget/embedded/src/components/CustomDestination/CustomDestination.types.ts, widget/embedded/src/types/config.ts, widget/embedded/src/utils/swap.ts
Every blockchain should be able to have a custom destination configured. (for example, Ethereum, Bitcoin, etc.) that are handle by a parameter in config
Add the customDestinations parameter to the config. 
In the config, add the value to customDestinations, and then try a swap on that blockchain.
=> feat: add defaultCustomDestinations param to config

scripts/build/command.mjs
Our scripts/build now accepts --inputs to accept more than one entry point. This is useful for supporting exports.
```
cd wallets/core
node ../../scripts/build/command.mjs --path wallets/core --inputs src/persistor.ts,src/index.ts
```
then check `/dist`, it should has two output: `index.js` and `persistor.js`
=> feat: accept multiple entrypoints for build script

widget/embedded/src/containers/Inputs/Inputs.tsx, widget/ui/src/containers/SwapInput/SwapInput.tsx, widget/ui/src/containers/SwapInput/SwapInput.types.ts
Hide balance and max button when no wallet connected in widget home page.
Fixes # 1678
Tested by checking home page when a wallet is connected and no wallet is connected.
=> feat: hide balance and max button when no wallet connected

widget/embedded/src/components/SwapDetails/SwapDetails.tsx
USD was missed for low values and also was incorrect in some cases in estimated output in swap details page. Fixed by removing a redundant normalizing.
Fixes # 1665
Tested by trying to swap below values and see the correct value in swap details page:
Ethereum.USDC:0.0001 => Ethereum.ETH
=> fix: fix missing usd value in estimated output

widget/embedded/src/store/quote.ts, widget/ui/src/containers/SwapInput/SwapInput.styles.ts, widget/ui/src/containers/SwapInput/SwapInput.tsx
Fixed bug in swap input handling empty value.
Fixes # 1668
Tested by entering zero and other values in swap input.
=> fix: fix bug in swap input handling empty value

.github/actions/upload-build-artifacts/action.yml
exclude tsconfig files from analyze bundle required artifacts to fix failing analyze bundle workflow.
=> chore: exclude tsconfig files from analyze bundle required artifacts

widget/embedded/src/containers/WidgetInfo/WidgetInfo.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.types.ts, widget/embedded/src/hooks/useUpdateQuoteInput/index.ts, widget/embedded/src/hooks/useUpdateQuoteInputs/index.ts, widget/embedded/src/hooks/useUpdateQuoteInputs/useUpdateQuoteInputs.ts, widget/embedded/src/types/quote.ts
To get the latest state of the quote inputs from outside the widget, we expose these states using the `useWidget` hook.
https://github.com/rango-exchange/rango-client/pull/815
=> chore: expose the quote inputs from the widget

widget/embedded/src/components/TokenList/TokenList.tsx, widget/embedded/src/hooks/useObserveBalanceChanges/index.ts, widget/embedded/src/hooks/useObserveBalanceChanges/useObserveBalanceChanges.ts
If we’re on the Token Selector page and the balance of the selected blockchain changes, the token list sort order fails to update.
=> fix: address the issue where the token list does not update when the balance changes

signers/signer-solana/src/signer.ts, signers/signer-terra/src/signer.ts, signers/signer-tron/src/signer.ts, wallets/provider-coin98/src/solana-signer.ts, wallets/provider-ledger/src/signers/ethereum.ts, wallets/provider-ledger/src/signers/solana.ts, wallets/provider-solflare-snap/src/signers/solanaSigner.ts, wallets/provider-xdefi/src/cosmos-signer.ts
Some providers have implemented a custom signer instead of using the base signers/implementations. We need to implement the `signMessage` method for these providers.
The `signMethod` of some default signers (Solana and Terra) didn't work as expected. These issues have also been addressed in this PR.
You can use the wallets-demo package and the sign buttons in the UI to test it.
(tron provider, coin98 solana provider, ledger ethereum and solana providers, solflare provider, xdefi cosmos provider)
You can test the default Solana signer with the Phantom wallet. However, we currently don't have any enabled wallets that support Terra, so there's no straightforward way to test it at this time. Code changes are needed to address this.
=> feat: implement sign message method for providers with a custom signer

widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx, widget/embedded/src/pages/WalletsPage.tsx
Fix bug related to closing wallet modal when it is being opened after another wallet is connected.
Connected a wallet and then immediately connected another wallet.
=> fix: fix wallet modal closing bug

widget/embedded/src/store/wallets.ts
When getWalletsDetails fails,
The error field for connected wallets is changed to `true`.
But the problem here is that it remains `true`.
And it will not be updated in the next successful request.
Now I solved this problem in such a way that when the request succeeds, it returns the error field to `false`.
For testing, you can link the `@rango-dev/widget-embedded` and use it in the `app` project and try again in the Wallet Details section after an error, and see the result.
=> fix: fix the issue with the wallets state after retrying to fetch the balance following a failed attempt.

examples/queue-manager-demo/src/flows/rango/helpers.ts, examples/wallets-demo/src/components/List/Item.tsx, examples/wallets-demo/src/helper.ts, queue-manager/rango-preset/src/helpers.ts, queue-manager/rango-preset/src/types.ts, wallets/core/legacy/package.json, wallets/core/package.json, wallets/core/src/legacy/helpers.ts, wallets/core/src/legacy/index.ts, wallets/core/src/legacy/mod.ts, wallets/core/src/legacy/types.ts, wallets/core/src/legacy/wallet.ts, wallets/core/src/mod.ts, wallets/react/src/index.ts, wallets/react/src/legacy/helpers.ts, wallets/react/src/legacy/hooks.ts, wallets/react/src/legacy/types.ts, wallets/shared/package.json, wallets/shared/src/rango.ts, widget/embedded/package.json, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/containers/Wallets/Wallets.types.ts, widget/embedded/src/containers/WidgetProvider/WidgetProvider.types.ts, widget/embedded/src/index.ts, widget/embedded/src/utils/wallets.ts, widget/embedded/tsconfig.build.json, widget/ui/package.json
Update all imports from `core` to import from `core/legacy` and move some functionality from `/shared` to `/core`.
In long term we will remove `wallets-shared`, a part of this PR is moving `core`-related functionality to `wallets-ocre`. And also this PR prefixed all the legacy core with `legacyThenSomething` to make sure we are flagging them and give a notice they are deprecated and will be removed in next major version.
In those packages who imported types or functions from legacy code, you will see I'm aliasing the `legacySomething` to `legacySomething as something`, this is because I wanted to update only imports and not the usages. I believe this is more appropriate way to reduce the changes.
module system other than `node16` and `bundler` doesn't have support for `package.json`'s …
=> chore: restructure shared and react to use /core package

examples/queue-manager-demo/src/flows/rango/helpers.ts, examples/wallets-demo/src/components/List/Item.tsx, examples/wallets-demo/src/helper.ts
Fix import from '@rango-dev/wallets-core/legacy' instead of '@rango-dev/wallets-core'  in examples.
=> chore: fix import from wallets core legacy in examples

signers/signer-solana/package.json, signers/signer-solana/src/signer.ts, wallets/provider-solflare-snap/package.json, wallets/provider-solflare-snap/src/signers/solanaSigner.ts, wallets/provider-solflare/package.json, wallets/provider-solflare/src/signers/solanaSigner.ts
update `signMessage` in the default Solana signer to return a base58 string instead of base64 .
You can test this change using the `wallets-demo` package.
=> fix: update `signMessage` in the default Solana signer to return a base58 string instead of base64

wallets/core/package.json
Include `legacy` folder on `core` publish.
We should allow `legacy` folder to be included in npm publish. you can take a look at [the original PR](https://github.com/rango-exchange/rango-client/pull/838) and more context on why we needed this at first place. 
After publishing `wallets-core` we can take a look at npm and see `legacy` exist or not.
=> chore: let legacy folder be included in wallets-core publish flow on npm

scripts/build/command.mjs, widget/embedded/src/components/StatefulConnectModal/index.ts, widget/embedded/src/hooks/useStatefulConnect/useStatefulConnect.state.ts, widget/embedded/src/index.ts
Export StatefulConnect components to share the logic between `embedded` and `dApp`.
It includes exporting required components for our dApp and one infrastructure change for our bundled libs (wc2, ledger and trezor) to make sure transforming dynamic `require`s to proper esm format. 
It will only affect the compilation and producing output.
=> feat: export StatefulConnect components and helpers

package.json, scripts/build/command.mjs, yarn.lock
Polyfill esbuild outputs to ensure it won't need to be polyfilled in host machines.
We are bundling some of dependencies directly into `dist` files (e.g. wc2), they may using internal node modules like `fs`. Our target is browser so we need to ensure we don't put any node-related modules inside our output.
You can make a local build and then `cd wallets/provider-walletconenct2 && yarn link` then in our dApp run `yarn link "@rango-dev/provider-walletconnect-2"` (next branch). Try to connect `Wallet Connect`, it should works.
=> fix: polyfill bundled dependencies

widget/embedded/src/components/Layout/Layout.tsx, widget/storybook/src/components/Header.stories.tsx, widget/ui/src/components/Header/Header.styles.ts, widget/ui/src/components/Header/Header.tsx, widget/ui/src/components/Header/Header.types.ts
Improved header component to center the title properly. In the result of these changes, the title in the header component is positioned correctly in the center of header and the position of title will not change in result of changing the width of prefix and postfix of header.
Fixes # 1674
If you compare header of the pages in this branch with production, you will see that title is centered regardless of width of prefix and postfix. You can test this by checking each header of each page to see everything is positioned properly.
=> fix: improve header component to center the title properly

wallets/provider-walletconnect-2/readme.md
We've had a change on our build scripts to include polyflls when needed. wc2 should be re-build to fix its issue `fs`.
=> chore: include polyfills for walletconnect-2 provider

widget/ui/src/components/Tabs/Tabs.styles.tsx, widget/ui/src/components/Tabs/Tabs.tsx
We need a different variant for the tabs component, similar to the one shown in this image: 
=> feat: implement bordered variant for tabs component

widget/ui/src/components/Modal/Modal.tsx
In certain cases, we want to conditionally remove the modal component from the DOM without using the close button or clicking the backdrop. Currently, the cleanup during the unmounting of the modal is not handled correctly. After the modal is removed from the DOM, the container's overflow remains set to "hidden," causing the scrollbar to stay hidden even after the modal is gone.
Removing the container's overflow property when the modal is unmounted.
You can test this by linking the UI package in the Dapp. Go to the profile page and attempt to log in. After logging in and the login modal is removed from the DOM, you'll notice that the body's overflow is incorrectly handled.
=> fix: ensure proper cleanup of the modal component after it is removed from the DOM

wallets/provider-all/src/index.ts, wallets/provider-trezor/notes.md, wallets/provider-trezor/package.json
Our dApp goes throw an error and it shows an error regarding `provider-trezor` can't be initialized by an incorrect import (`.default`). you can take a look at RF-1838 for more context.
In this PR, we are removing bundling for `connect-web` package. Take a look at `notes.md` for more information.  
Try to run `yarn build:all` and then link to our dApp. Trezor should be in the list and works correctly.
=> fix: enabling trezor by removing bundling for @trezor/connect-web

wallets/provider-ledger/package.json
Making ledgerhq dependencies internal made bundle size to increase about 2MBs. So we decided to remove them from internal packages.
=> chore: remove ledgerhq dependencies from internal packages

widget/storybook/src/components/Tabs/Tabs.stories.tsx, widget/storybook/src/components/Tabs/mock.tsx, widget/ui/src/components/Tabs/Tabs.styles.tsx, widget/ui/src/components/Tabs/Tabs.tsx, widget/ui/src/components/Tabs/Tabs.types.tsx
We need a scrollable variant for the Tabs component in the Dapp. I attempted to implement a solution similar to Material UI's scrollable tabs. You can check it out here:
https://mui.com/material-ui/react-tabs/#scrollable-tabs
=> feat: implement scrollable variant for Tabs component

wallets/provider-exodus/src/helpers.ts, wallets/provider-taho/src/helpers.ts, wallets/provider-xdefi/src/cosmos-signer.ts, wallets/provider-xdefi/src/helpers.ts, wallets/shared/src/rango.ts
RF-1900: Bep2 network is deprecated. We should deprecate supporting it gradually. I've removed its supprot in XDEFI wallet.
=> chore: deprecate bep2 support

wallets/provider-xdefi/src/cosmos-signer.ts, wallets/provider-xdefi/src/helpers.ts, wallets/provider-xdefi/src/utxo-signer.ts
Null memo is removed from utxo transactions and undefined will be passed instead of that.
=> fix: remove null memo from utxo transactions

signers/signer-solana/src/signer.ts, signers/signer-solana/src/utils/types.ts, wallets/provider-brave/src/signer.ts, wallets/provider-brave/src/solana-signer.ts, wallets/provider-clover/package.json, wallets/provider-clover/src/signer.ts, wallets/provider-clover/src/solana-signer.ts, wallets/provider-coinbase/package.json, wallets/provider-coinbase/src/signer.ts, wallets/provider-coinbase/src/solana-signer.ts, wallets/provider-exodus/package.json, wallets/provider-exodus/src/signer.ts, wallets/provider-exodus/src/solana-signer.ts, wallets/provider-okx/src/signer.ts, wallets/provider-okx/src/solana-signer.ts, wallets/provider-xdefi/package.json, wallets/provider-xdefi/src/signer.ts, wallets/provider-xdefi/src/solana-signer.ts
Some Solana providers use the default `Solana signer`, but when testing the `signMessage` method, it either throws an error or doesn't function correctly
You can test this by running the `yarn dev:wallets` command and using the `signMessage` method in the `wallets-demo` UI. The `signMessage` method for the `Coinbase` provider doesn’t work correctly on localhost. To test it, you can copy and paste the code into the console on the live production site.
=> fix: resolve issues with the `signMessage` method for certain `Solana`

scripts/build/command.mjs, wallets/provider-coin98/package.json, wallets/provider-ledger/package.json, wallets/provider-math-wallet/package.json, wallets/provider-safe/package.json, wallets/provider-solflare-snap/package.json, wallets/provider-solflare/package.json, wallets/provider-trezor/package.json, wallets/provider-walletconnect-2/package.json, wallets/provider-xdefi/package.json
Enabled code splitting in build options of esbuild. Code splitting is still a work in progress in [esbuild docs](https://esbuild.github.io/api/#splitting) because it only works with `esm` output format (which we currently use) and it has a [known ordering issue](https://github.com/evanw/esbuild/issues/399). I'm not sure if we may encounter that issue but the is a [workaround](https://github.com/evanw/esbuild/issues/399#issuecomment-1458680887) introduced to prevent that. You can follow [the tracking issue](https://github.com/evanw/esbuild/issues/16) for updates about this feature. 
After applying this change and testing it through linking `widget-embedded` package in `app` repo, I observed that bundle size is reduced to 1.4MBs.
Fixes # 1905
Please describe the tests that you ran to verify …
=> perf: enable code splitting in build process

widget/ui/src/components/Tabs/Tabs.tsx
- When the container of the Tabs component resizes, the tabs don't adjust properly, which can result in incorrect tab or indicator widths.
- In the scrollable variant, the scroll functionality sometimes fails when we reach the start or end of the list 
https://github.com/user-attachments/assets/5ece03e1-1ee3-4aa7-bf1b-1f7e6102c081
- I've also added a data-active attribute to the Tab component so that active and inactive tabs can be targeted externally.
=> fix: fix issues in the tabs component

wallets/provider-trezor/src/signers/ethereum.ts
Currently, using the `Trezor` provider's `signMessage` method results in an error. We mistakenly used the `signMessage` method, but we should be using the `ethereumSignMessage` method instead.
=> fix: resolve issues with Trezor provider's sign message method

wallets/provider-solflare/src/index.ts
Get correct instance for CJS hosts.
We've got a report regarding `next@13` and `module: esnext`, `moduleResolution: node` can not be run and throwing an error on `provider-solflare`.
=> fix: when host is using cjs, fallback to .default() for solfare sdk

scripts/crowdin/pretranslate.mjs
To switch the translation engine, the Google Machine Translation Engine ID is required
=> fix: change crowdin machine translation to google translate

.github/workflows/checks.yaml, scripts/lingui/command.js
Added extract translations job to check workflow. Also added a wrapper on extract translations in check workflow to exit if there is an error in extract flow which does not force workflow to fail.
Fixes # 1873
Ran Github workflow.
=> chore: add extract translations job to check workflow

widget/ui/src/components/Tooltip/Tooltip.tsx, widget/ui/src/components/Tooltip/Tooltip.types.ts
Collision padding refers to the space that is added around the tooltip to ensure that it does not collide with the edges of its container or other UI elements. This padding helps to prevent the tooltip from being positioned too close to the boundaries of the viewport or overlapping with other components, which can enhance usability and visibility.
=> feat: add a prop to the tooltip component for collision padding

widget/charts/src/components/BarChart/BarChart.tsx
In small datasets, when the sum of the numbers is less than 0.5, the y-axis is not displayed correctly.
=> fix: y-axis display for Small data sets

wallets/provider-keplr/package.json
Resolution only works in one depth, for transitive packages we should set the whole path.
=> chore: set a resolution for protobufjs transitive package

wallets/provider-walletconnect-2/package.json
Resolution only works in one depth, for transitive packages we should set the whole path.
=> chore: set a resolution for protobufjs transitive package in wc2

widget/embedded/src/hooks/useSwapInput.ts, widget/embedded/src/store/slices/data.ts, widget/embedded/src/types/config.ts, widget/embedded/src/utils/settings.ts, widget/embedded/src/utils/swap.ts
We needed to add `avoidNativeFee` and `maxLength` to features, but after speaking with @RanGojo and @yeager-eren, we concluded that we should create a new parameter called `routing`. This parameter will contain `avoidNativeFee`, `maxLength`, and `experimental`.
=> feat: add routing parameters to widget config

widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.helpers.ts
When a 400 Bad Request error occurs during a swap attempt, the error message displayed to the user is "`Failed Network, Please retry your swap.`" This message is misleading as it implies a network issue rather than a client-side request error.
I handled these bad requests by using the error code `ERR_BAD_REQUEST` and typing `NO_RESULT`.
You can create this bad request by setting the `slippage` above `30`.
=> fix: fix error display for bad requests

docs/code-splitting.md, wallets/provider-argentx/src/signer.ts, wallets/provider-bitget/src/signer.ts, wallets/provider-braavos/src/signer.ts, wallets/provider-brave/src/signer.ts, wallets/provider-clover/src/signer.ts, wallets/provider-coin98/package.json, wallets/provider-coin98/src/signer.ts, wallets/provider-coinbase/src/signer.ts, wallets/provider-exodus/src/signer.ts, wallets/provider-frontier/src/signer.ts, wallets/provider-ledger/src/signers/ethereum.ts, wallets/provider-ledger/src/signers/solana.ts, wallets/provider-math-wallet/src/signer.ts, wallets/provider-mytonwallet/src/signer.ts, wallets/provider-okx/src/signer.ts, wallets/provider-phantom/src/signer.ts, wallets/provider-safepal/src/signer.ts, wallets/provider-solflare-snap/package.json, wallets/provider-solflare-snap/src/signer.ts, wallets/provider-solflare/package.json, wallets/provider-solflare/src/signer.ts, wallets/provider-tron-link/src/signer.ts, wallets/provider-xdefi/src/cosmos-signer.ts, wallets/provider-xdefi/src/signer.ts
Added a document for `code-splitting` and also detected some dynamic imports which result in small chunks and reverted such dynamic imports. I've added list of files resulted in build process in `widget-examples\vite`
Build result before code splitting:
```
dist/index.html                              0.46 kB │ gzip:     0.30 kB
dist/assets/index-a2801db4.css               0.04 kB │ gzip:     0.06 kB
dist/assets/index-992cec4c.js                0.98 kB │ gzip:     0.46 kB
dist/assets/index-206c2777.js                3.23 kB │ gzip:     1.29 kB
dist/assets/Solana-91a6328d.js               3.78 kB │ gzip:     1.64 kB
dist/assets/TransportWebHID-b0074475.js     33.78 kB │ gzip:    11.55 kB
dist/assets/index-096a66d2.js              139.07 kB │ gzip:    44.07 kB
dist/assets/index-21326ca8.js …
```
=> chore: improve and document code splitting

signers/signer-solana/src/utils/send.ts
Update solana confirmation timeout from 30s to 60s.
(The maximum age of a transaction's blockhash is 150 blocks (~1 minute assuming 400ms block times). If a transaction's blockhash is 150 blocks older than the latest blockhash, it is considered expired. This means that transactions not processed within a specific timeframe will never be executed.)
=> chore: update solana confirmation timeout

widget/embedded/src/components/NoResult/NoResult.helpers.ts, widget/embedded/src/components/SameTokensWarning/SameTokensWarning.styles.ts, widget/embedded/src/components/SameTokensWarning/SameTokensWarning.tsx, widget/embedded/src/components/SameTokensWarning/index.ts, widget/embedded/src/pages/Home.tsx
If the source and destination tokens are selected as the same, we should show a warning to the user.
Select the same token for both the source and destination, and also enter an amount
=> feat: display same source and destination token warning on widget

wallets/core/src/namespaces/evm/actions.ts, wallets/react/src/hub/utils.ts
Add `changeChainSubscriber` to evm namespace.
I took this branch from the `feat/support-for-both-legacy-and-hub` branch in this [PR](https://github.com/rango-exchange/rango-client/pull/852).
=> feat: add chain change subscribe to evm namespace

widget/embedded/src/store/slices/data.ts, widget/playground/src/store/meta.ts
Currently, disabled swappers are visible in widget settings, which could lead to unintended usage in various sections of the application. This update ensures that disabled swappers are:
- Not displayed to users in the widget interface.
- Prevented from being used in any functionality.
=> fix: improve handling of disabled swappers in widget

widget/embedded/src/hooks/useFetchCustomToken.ts
This PR resolves an issue where the error message wasn't displayed correctly when a `token not found` error was received from the server. The fix ensures that the appropriate error message is shown to the user.
=> fix: handle token not found error for custom tokens

wallets/core/namespaces/common/package.json, wallets/core/namespaces/evm/package.json, wallets/core/namespaces/solana/package.json, wallets/core/src/legacy/mod.ts, wallets/core/src/legacy/types.ts, wallets/core/src/legacy/utils.ts, wallets/core/src/namespaces/common/mod.ts, wallets/core/src/namespaces/common/types.ts, wallets/provider-ledger/src/index.ts, wallets/provider-trezor/src/index.ts, wallets/react/src/hub/autoConnect.ts, wallets/react/src/hub/useHubAdapter.ts, wallets/react/src/hub/utils.ts, wallets/shared/src/rango.ts, widget/embedded/src/components/StatefulConnectModal/StatefulConnectModal.tsx, widget/embedded/src/components/WalletStatefulConnect/DerivationPath.helpers.ts, widget/embedded/src/components/WalletStatefulConnect/Namespaces.tsx, widget/embedded/src/components/WalletStatefulConnect/Namespaces.types.tsx, widget/embedded/src/hooks/useStatefulConnect/useStatefulConnect.ts, widget/embedded/src/hooks/useStatefulConnect/useStatefulConnect.types.ts, widget/embedded/src/types/wallets.ts, widget/embedded/src/utils/hub.ts
Using a single source of truth for Namespace.
We need to use a single type for both legacy and hub implementation. To make it more general and don't needing to always keeping the namespace updated by what Rango currently support, I changed it to `string`, instead of enum. To have namespace suggestion while coding, I used a trick to suggest our supported namespaces alongside the fact that it can be any string.
It should be compiled correctly, shouldn't affect the functionality of working with wallets.
=> chore: change Namespace enum to stirng

wallets/core/src/namespaces/evm/actions.ts, wallets/react/src/hub/autoConnect.ts, wallets/react/src/hub/lastConnectedWallets.ts, wallets/react/src/hub/useHubAdapter.ts
Keep full namespace input in storage.
Previously we've stored the wallet name only, for hub we extended it to store namespace name as well. But we need the full namespace input (namespace name and network) to be stored.
You can take a look at localstorage data in your browser. Phantom is currently the only wallet that is using hub.
=> feat: storing network alongside namespace for hub localstorage

queue-manager/rango-preset/src/actions/checkStatus.ts, queue-manager/rango-preset/src/actions/executeTransaction.ts, queue-manager/rango-preset/src/helpers.ts, queue-manager/rango-preset/src/index.ts, queue-manager/rango-preset/src/services/eventEmitter.ts, queue-manager/rango-preset/src/shared.ts, queue-manager/rango-preset/src/types.ts, wallets/core/src/legacy/mod.ts, wallets/core/src/legacy/types.ts, wallets/core/src/legacy/utils.ts, wallets/react/src/hub/autoConnect.ts, wallets/react/src/hub/useHubAdapter.ts, wallets/react/src/hub/utils.ts, wallets/react/src/legacy/useLegacyProviders.ts, widget/embedded/src/QueueManager.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.helpers.ts
Remove DISCOVER_MODE from hub's adapter.
Originally, I didn't want to change the usage of `wallets-core` in `embedded` but there is a difference between legacy and hub and that is hub needs to pass `namespace` for connecting. legacy didn't have the namespace concept at all and you could connect using `network`. To make these compatible with each other, I created a hardcoded `network` -> `namespace` map in adapter.
This works but it's not and ideal way to use and keep. In this PR I removed this mode from hub and did the necessary changes to `embedded` code (specifically, `rango-preset`) to have namespace and pass it to hub. 
Fixes RF-1967
There are two commits, first commit removed the DISCOVER_MODE from our wallet management. The second commit introduced the concept of `namespace` to …
=> chore: remove discover mode from hub adapter

wallets/core/src/namespaces/common/builders.ts, wallets/core/src/namespaces/evm/actions.ts, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/store/slices/wallets.ts
Fix updating balances when switching network in wallet.
We've changed how we store balances in our app, in our new approach we are caching the balances somehow. We need to clean up these cache when switching account for a wallet.
Fixes RF-2051
Try to switch account in your wallets, balances should be updated correctly. This is not only related to Hub compatible wallets, legacy wallets have been affected. So please check with some of your installed wallets including Phantom and other wallets you may have.
=> fix: clean up old balances when switching account

wallets/react/src/hub/autoConnect.ts, wallets/react/src/hub/useHubAdapter.ts, wallets/react/src/legacy/types.ts, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/utils/providers.ts
1. When hub attempts to auto connect some wallets which are removed from widget config, it results in crashing the app. This problem is resolved in this PR by checking wallets config before performing auto connect.
2. If list of wallets is given as config to widget which includes a wallet with version "1", it fails to pick both versions for that provider and results in app crash. This problem is fixed in the second commit.
1. Tested by connecting a wallet which supports auto connect and then remove that wallet from wallets config and refreshing the page. By doing this no crash should happen.
2. Tested by including 'phantom' in widget config wallets.
=> fix: fix hub bugs with wallet list

widget/playground/src/constants/languages.ts, widget/playground/src/containers/StyleLayout/StyleLayout.General.tsx
The default language in the settings is set to "Afrikaans" instead of "English".
=> fix: incorrect default language setting

widget/embedded/src/components/SwapDetailsModal/SwapDetailsCompleteModal.tsx, widget/embedded/src/hooks/useFetchApiConfig.ts, widget/embedded/src/store/ui.ts, widget/embedded/tsconfig.json
In the `config` API, we have an object named `banners` that has a boolean object named `profile`. If it is `true`, we need to display the profile banner in the widget success modal.
=> feat: add profile banner to widget success modal

wallets/core/src/legacy/wallet.ts, wallets/provider-keplr/src/helpers.ts, wallets/provider-keplr/src/index.ts
Avoid CTRL to override the function named `keplr`.
We've faced with a weird bug where Having CTRL and Keplr at the same time causing an app crash. The first investigation was changing the getInstance from function declaration to arrow function in keplr provider will fix the issue. After more investigation I tried to see the difference between these two function declaring to find the root cause.
here is the transpiled verson for function declariont (simplified):
```js
var c = Object.defineProperty;
var r = (e, o) => c(e, "name", {
value: o,
configurable: !0
});
function s() {
return window.keplr || null
}
r(s, "keplr");
// then export s as getInstance
```
and arrow function:
```js
r(() => window.keplr || null, "getInstance")
// then export.
```
the only difference is in the first one, the …
=> fix: ctrl wallet is changing 'keplr' named function to undefined

widget/embedded/src/containers/WidgetInfo/WidgetInfo.tsx, widget/embedded/src/containers/WidgetInfo/WidgetInfo.types.ts, widget/embedded/src/store/slices/wallets.ts, widget/embedded/src/store/utils/wallets.ts
Add `balances` to WidgetInfo's `wallets.details`.
In https://github.com/rango-exchange/rango-client/pull/852, we refactored the wallets store and a part of that was logic related to `ConnectedWallet`. After refactoring, we've removed a field from the object called `balances`. since this was exposed to outside world using `WalletInfo` we need to revert it back for backward compatibility. (used in our dApp as well.)
Don't need to test, it will be tested in https://github.com/rango-exchange/app-v2/pull/145.
=> fix: adding balances to ConnectedWallet for WidgetInfo

widget/embedded/src/utils/wallets.ts
Fix total balance amount.
It should consider decimals first, then calculate the total balance.
No need to test. will be tested on dApp.
=> fix: fix total balance calculation for WidgetInfo

widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/components/StatefulConnectModal/StatefulConnectModal.tsx
Wallet connection modal was not closing automatically after connecting a wallet which needs namespace selection or derivation path entering. It is fixed by calling `afterConnect` method after connecting wallet with namespace or derivation path.
Fixes # 2147
Tested by connecting a wallet which needs namespace or derivation path (such as phantom and ledger) and observing that wallet connection modal closes automatically after successful connect.
=> fix: close wallet connection modal after connect with namespace

widget/embedded/src/utils/wallets.ts
In [another PR](https://github.com/rango-exchange/rango-client/pull/993) I tried to fix total balance for our dApp integration. I used `formatBalance` to convert amount (pair of amount and decimals) to be represented in decimal format. That function do this but also will format the output to separate numbers by comma (`1,350`). For the calculation I only need the represented value. 
Will be tested in https://github.com/rango-exchange/app-v2/pull/145
=> fix: usdValue shouldn't be formatted to calculate the total value

wallets/react/src/hub/autoConnect.ts, wallets/react/src/hub/lastConnectedWallets.ts, wallets/react/src/hub/useHubAdapter.ts, wallets/react/src/hub/utils.ts
Fixed two bugs:
Update connected namespaces for wallets in storage on switch account
Fixes # (RF-2098)
Tested this change by connecting phantom wallet on solana namespace. Observed that solana namespace is set in local storage in `hub-v1-last-connected-wallets` for phantom wallet. After that I switch to an account which only contains ethereum address and observed that local storage updated as result of disconnecting wallet.
=> fix: update connected namespaces in storage on switch account

wallets/react/src/hub/autoConnect.ts, wallets/react/src/hub/helpers.ts, wallets/react/src/legacy/autoConnect.ts
Remove namespace from storage on auto connect failure. 
Fixes # (RF-2118)
Tested this change by changin phantom account to an account containg only Solana address and setting `{"phantom":[{"namespace":"Solana"},{"namespace":"EVM"}]}` value for `hub-v1-last-connected-wallets` in localStorage and refreshing the app. Observed that Solana namespace connected successfully and also EVM namespace removed from localstorage.
=> fix: remove namespace from storage on auto connect failure

wallets/react/src/hub/utils.ts, wallets/react/src/legacy/types.ts, wallets/react/src/useProviders.ts, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/hooks/useWalletList.ts, widget/embedded/src/store/slices/config.ts, widget/embedded/src/store/slices/data.test.ts, widget/embedded/src/types/config.ts, widget/embedded/src/utils/providers.ts, widget/embedded/src/utils/settings.ts, widget/playground/src/App.tsx, widget/playground/src/containers/FunctionalLayout/FunctionalLayout.Wallets.tsx
Removed `experimentalWallets` from widget config because it is no longer needed and we enabled that feature by default.
=> chore: remove experimental wallets from widget config

wallets/react/src/hub/mod.ts, wallets/react/src/hub/utils.ts, wallets/react/src/index.ts, widget/playground/src/containers/FunctionalLayout/FunctionalLayout.Wallets.tsx
In some places we used `separateLegacyAndHubProviders` without any config to access only legacy providers which was unsafe and produced some issues after removing the `experimentalWallet` config. It is fixed by defining a seperate function for accessing legacy providers.
=> chore: refactor get legacy providers

wallets/shared/src/helpers.ts
Resolved an issue in the Phantom wallet related to connecting to the Solana namespace. Previously, after disconnecting the wallet and attempting to reconnect to both Solana and EVM namespaces, errors occurred with the Solana instance. This problem was fixed by modifying the connection process to the Solana namespace, ensuring that account requests are not sent if the public key is already available.
Connected to Solana namespace, then disconnected and then connected to both namespaces. Observed that both namespaces get connected without any error.
=> fix: resolve issue with connecting to solana namespace

wallets/react/src/hub/utils.ts
This pull request addresses an inconsistency related to disconnecting Phantom wallets after switching to an account that does not contain both Solana and EVM addresses. Previously, when transitioning from an account with both addresses to one containing only the EVM address, only the Solana account would disconnect. Conversely, moving from an account with both addresses to one with only the Solana address resulted in both Solana and EVM accounts disconnecting.
This PR resolves the issue by ensuring that when switching from an account containing both addresses to one with only either the EVM or Solana address, only the connection to the unavailable address is disconnected. This enhancement provides a more coherent and expected behavior during account transitions.
Fixes # 2141
Please …
=> fix: fix incorrect wallet state after switch account

wallets/react/package.json, wallets/react/src/hub/autoConnect.ts, wallets/react/src/hub/helpers.ts, wallets/react/src/hub/useHubAdapter.ts, yarn.lock
This pull request addresses an issue with connecting to namespaces on the Phantom wallet. That issue was happening in this scenario: Imagine you have two accounts on Phantom which one of them supports both evm and solana and the other one only supports solana address and widget does not have access to connect each of them. First, we try to connect to the account which only supports solana. After it gets connected successfully, we disconnect it and switch to the other account which supports both namespaces on Phantom. Now, if we try to connect to that account, it fails on connecting to solana namespace. After some investigation, it turned out that there is a problem on Phantom extension which fails to address two parallel requests in this scenario.
In this PR, connecting to namespaces has …
=> fix: make connect namespaces sequential

queue-manager/rango-preset/src/helpers.ts
Display correct network in switch network modal instead of always displaying ethereum.
This change can be tested by setting Metamask on a different network and initiating a transaction and observing that the correct network is displayed in the modal.
=> fix: display correct network in switch network modal

widget/embedded/src/store/slices/wallets.ts
Details related to unsupported tokens was missed in return value of `getConnectedWalletsDetails` leading to not appearing those tokens and balances in wallets details sidebar in app. In result of this change, it is fixed and unsupported tokens can be found in wallet details sidebar.
This can be tested on app (after linking this changes to "upgrade to hub" PR on APP) by checking for unsupported tokens in wallets details sidebar.
=> fix: add unsupported tokens to wallets details

wallets/core/package.json, wallets/core/src/hub/store/events.ts, wallets/core/src/hub/store/extend.ts, wallets/core/src/hub/store/mod.ts, wallets/core/src/hub/store/namespaces.ts, wallets/core/src/hub/store/providers.ts, wallets/core/src/hub/store/store.test.ts, wallets/core/src/hub/store/store.ts, wallets/core/src/legacy/types.ts, wallets/core/src/legacy/wallet.ts, wallets/core/src/namespaces/evm/builders.ts, wallets/core/src/namespaces/solana/builders.ts, wallets/react/src/hub/useHubAdapter.ts, wallets/react/src/hub/utils.ts, wallets/react/src/legacy/types.ts, widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/store/slices/wallets.ts
Introducing store events to fix switching accounts issues.
We've been used an observer on store in `wallets-react` to compare two states and firing legacy events. In this PR, I tried to add the event system to Hub's store. Besides the legacy events, we've have new ones which mapped or the proper logic added to the flow.
Fixes RF-2252
Just run the widget then try to switch account on your Phantom wallet. You can check some legacy wallets as well.
=> feat: introducing store events for hub and fix switching accounts issues

wallets/core/src/legacy/types.ts, wallets/provider-phantom/src/constants.ts
Phantom Wallet has added support for the Base chain, which means we can now include Base in the list of supported chains.
=> feat: add base chain to phantom evm supported chains

widget/embedded/src/store/slices/wallets.ts
After a transaction gets executed, balance for that wallet address will be fetched for source and destination wallet address and blockchain, then new balances will be set in store and already existing balances will be updated, but old balances are not getting removed. This results in that if a transaction get executed with max amount for an asset, there will be no balance related to that asset in the response of fetch balance so old balance for that asset will not get removed from store.
As a result of this change, the old balances will be removed initially, followed by the application of updates to address the described issue.
Fixes # 2231
Create a transaction with max amount of source asset. After executing the transaction successfully, you should observe that balances get updated …
=> fix: update balance after transaction with max amount

widget/embedded/src/constants/wallets.ts, widget/embedded/src/store/slices/wallets.ts, widget/embedded/src/store/utils/wallets.ts
Currently, balances are stored by keys composed of BlockchainId, TokenAddress, TokenSymbol, WalletAddress separated by `-`. This creates problem if there be a `-` in token symbol or blockchainID. In this PR, separator is changed to `$$` and also is used as a variable to make it easy to work with.
Tested by connecting some wallets and observing balances for related tokens.
=> fix: change balance key separator

widget/embedded/src/constants/wallets.ts
Currently, balance key separator is equal to `$$`. It has conflict with some tokens like `GEO$`. 
In this PR it is changed to `~` considering that there is no token in meta containing this character.
=> chore: update balance key separator

wallets/react/src/hub/useHubAdapter.ts
Fixed incorrect default install link for wallets.
It can be tested by checking install link for Phantom wallet in Firefox browser.
=> fix: fix incorrect default install link

wallets/core/src/legacy/types.ts, wallets/react/src/hub/utils.ts, widget/embedded/src/containers/Wallets/Wallets.helpers.ts, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/containers/Wallets/Wallets.types.ts, widget/embedded/src/containers/Wallets/useUpdates.ts, widget/embedded/src/store/slices/wallets.ts
There was a bug in disconnecting a namespace for a wallet which that caused incorrect state for wallet. Consider you connect to a wallet on both namespaces and after that one namespace gets disconnected (for example n result of switching to an account which does not support one of namespaces). In this scenario, old balances for disconnected namespace gets cleared but it won't be removed from connected wallets. In this PR, after disconnecting a namespace, the connected wallets in wallet slice related to that namespace get cleared instead of just balances being cleared.
You can test this change by repeating this scenario:
1. Connect to an account on Phantom with both EVM and  Solana namespaces.
2. Select an EVM and a Solana token and navigate to confirm wallets page.
3. …
=> fix: remove connected wallet on namespace disconnect

widget/embedded/src/hooks/useSubscribeToWidgetEvents/useSubscribeToWidgetEvents.ts
The issue with balance updates not functioning correctly was due to a scenario where two wallets sharing the same blockchain were connected as either the 'from' or 'to' account in a transaction. This problem has been resolved by implementing a solution that involves identifying the correct wallet for updating the balance. This is achieved by not only considering the blockchain of the account but also evaluating the address and type of wallet associated with the account.
Fixes # 2291
It can be tested by connecting Metamask and Phantom on EVM and executing transaction with Phantom and observing that balances get updated properly.
=> fix: fix balance not updating properly after transaction

widget/embedded/src/containers/Inputs/Inputs.tsx
There was an issue happening on clicking on max button with balance of more than 1000 units which was causing an empty input amount and Nan for value of input amount.
It is fixed the way it was working before [this](https://github.com/rango-exchange/rango-client/commit/a14bdf9619e448bc4568d6b758ca86d2359e1740#diff-9edb2091bb12bc14426dc63306f12e3356cef0b428425161bfc44f6a4f079275L110) commit change its behavior.
You can test this change by clicking on max button with more that 1000 units balance for a token and observe that it sets the input amount properly.
=> fix: fix incorrect input amount on max button click

wallets/core/namespaces/sui/package.json, wallets/core/package.json, wallets/core/src/hub/provider/types.ts, wallets/core/src/legacy/types.ts, wallets/core/src/namespaces/common/types.ts, wallets/core/src/namespaces/sui/actions.ts, wallets/core/src/namespaces/sui/builders.ts, wallets/core/src/namespaces/sui/constants.ts, wallets/core/src/namespaces/sui/mod.ts, wallets/core/src/namespaces/sui/types.ts, wallets/core/src/namespaces/sui/utils.ts
Adding standard methods to hub for sui.
`connect`, change account subscriber and get instance has been implemented by wallet-standard spec. which means all Sui wallet can use these (including Phantom)
You can test on the [Phantom's PR](https://github.com/rango-exchange/rango-client/pull/1015). To be able to build, you need to link this [PR as well](https://github.com/rango-exchange/rango-types/pull/44).
=> feat: add sui namespace to wallets-core

wallets/core/namespaces/utxo/package.json, wallets/core/package.json, wallets/core/src/hub/mod.ts, wallets/core/src/hub/namespaces/mod.ts, wallets/core/src/hub/provider/types.ts, wallets/core/src/mod.ts, wallets/core/src/namespaces/utxo/actions.ts, wallets/core/src/namespaces/utxo/after.ts, wallets/core/src/namespaces/utxo/and.ts, wallets/core/src/namespaces/utxo/before.ts, wallets/core/src/namespaces/utxo/builders.ts, wallets/core/src/namespaces/utxo/constants.ts, wallets/core/src/namespaces/utxo/mod.ts, wallets/core/src/namespaces/utxo/types.ts, wallets/provider-phantom/package.json, wallets/provider-phantom/src/constants.ts, wallets/provider-phantom/src/legacy/index.ts, wallets/provider-phantom/src/legacy/signer.ts, wallets/provider-phantom/src/legacy/utxoSigner.ts, wallets/provider-phantom/src/namespaces/utxo.ts, wallets/provider-phantom/src/provider.ts, wallets/provider-phantom/src/utils.ts, wallets/react/src/hub/autoConnect.ts, wallets/react/src/hub/helpers.ts, wallets/react/src/hub/useHubAdapter.ts, wallets/shared/src/rango.ts, yarn.lock
Added connect and sign transaction on Bitcoin using Phantom Wallet.
This change can be tested by connecting, switching account and signing transactions on Bitcoin using Phantom wallet.
=> feat: add bitcoin signer for phantom on hub

wallets/provider-solflare-snap/package.json, wallets/provider-solflare/package.json, wallets/provider-trezor/package.json, yarn.lock
Hello from Trezor,
We noticed that you are using an older version of the @trezor/connect-web library, which we are planning to deprecate in the upcoming months.
This PR updates it to the latest version to ensure continued compatibility.
=> chore: update @trezor/connect-web to 9.5.0

widget/embedded/src/hooks/useSwapInput.ts, widget/embedded/src/store/slices/wallets.ts, widget/embedded/src/types/wallets.ts, widget/embedded/src/utils/swap.ts, widget/embedded/src/utils/wallets.ts
If certain routes involve smart wallets, user funds could become trapped in the underlying bridge.  
To prevent this, we can add a `contractCall` parameter to the routing request, informing the API and ensuring that routes for these problematic wallets are not generated.
You can create an account in the Safe Wallet app, build the widget, and copy the `manifest.json` file into the `dist` folder of the widget app package. Then, serve it using the command `serve -C` and test this pull request's functionality by adding the widget app as a Safe custom app.
=> fix: avoid problematic routes for contract wallets

widget/embedded/src/store/slices/settings.ts, widget/embedded/src/store/slices/wallets.ts, widget/embedded/src/store/utils/wallets.ts
We want to fetch the balances of custom tokens for wallets that support the corresponding blockchains whenever new custom tokens are added or a new wallet is connected.
Also implementing the retrieval of the token price from the balances response and updating the `usdValue` in the balance cache.
You can add a custom token or connect a wallet that supports the blockchain of the custom tokens. A request will be sent to the server to fetch the balances of those tokens.
Sample test case:
3yoMkf3X6bDxjks6YaWwNk4SAbuaysLg1a4BjQKToQAA
=> feat: fetch balance for custom tokens

widget/embedded/src/hooks/useSubscribeToWidgetEvents/useSubscribeToWidgetEvents.ts
Resolve "wallet is possibly undefined error" in `useSubscribeToWidgetEvents` to avoid runtime errors.
=> fix: resolve wallet is possibly undefined error in useSubscribeToWidgetEvents

widget/embedded/src/store/slices/wallets.ts
Currently, there are two places in `fetchBalances` action in `wallets` slice in which we throw an error but we do not handle that error in places we initiate `fetchBalances`. Also there is another action named `fetchCustomTokensBalance` which has a similar functionality but it just log errors in console instead of throwing errors. 
To ensure consistency and reduce the need for error handling in multiple places, this PR replaces error throwing with `console.error in the `fetchBalances` action, aligning it with the `fetchCustomTokensBalance` behavior.
=> chore: avoid throwing error in fetch balances

widget/embedded/src/store/middlewares/keepLastUpdated.ts, widget/embedded/src/store/slices/wallets.ts, widget/embedded/src/store/utils/wallets.ts
Reduce state updates (calling `set`) by batching them into one update.
In `fetchBalances` we were updating `balances` and `aggregatedBalances` twice. each of them update the UI synchronously which means it was a render blocking operation. Also calling `fetchBalances` multiple times (during renders and connecting wallets) causes CPU be blocked for a noticeable time. 
In this PR, I made the remove operation into a util, then on fetching balances to batch the update, used that util.
Another change is in our middleware I changed it in someway to update the upcoming change and `lastUpdatedTime` in one update.
The bug reported on Parcel, so you need to link this PR and then try to test. Please consider to test `fetchingBalances` scenarios which means on …
=> fix: batching state updates for fetchBalances

widget/embedded/src/components/Layout/Layout.tsx
There was a problem on showing swap box banner on initial page loads on production environment. The problem was related to that the banner was showing if `showBanner` flag was equal to try. `showBanner` was calculated in a `useMemo` with these dependencies: `__UNSTABLE_OR_INTERNAL__?.swapBoxBanner?.routes?.toString()`. Considering this implementation, if `__UNSTABLE_OR_INTERNAL__` is populated after the initial render (e.g., through an async operation or late initialization), `useMemo` will cache the initial undefined state and won't update until one of the dependencies changes.
In this PR, that is handled using a `useEffect` hook to detect that if `__UNSTABLE_OR_INTERNAL__` is injected.
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
=> fix: fix banner not showing on initial page load

widget/embedded/src/hooks/useSubscribeToWidgetEvents/useSubscribeToWidgetEvents.ts, widget/embedded/src/store/slices/settings.ts, widget/embedded/src/store/slices/wallets.ts
Currently, there's a bug where if a user imports a custom token and then connects a wallet that supports the blockchain of that token, the custom token’s balance might not be displayed. This issue occurs when the request to fetch wallet balances resolves after the request for custom token balances, causing the custom token balance to be removed from the store once the wallet details request completes.
=> fix: fetch custom tokens balances after wallets balances

wallets/core/src/hub/namespaces/types.ts, wallets/core/src/namespaces/cosmos/types.ts, wallets/core/src/namespaces/evm/actions.ts, wallets/core/src/namespaces/evm/builders.ts, wallets/core/src/namespaces/evm/types.ts, wallets/core/src/namespaces/solana/types.ts, wallets/core/src/namespaces/sui/types.ts, wallets/core/src/namespaces/utxo/types.ts, wallets/provider-phantom/src/namespaces/evm.ts, wallets/provider-phantom/src/namespaces/solana.ts, wallets/provider-phantom/src/namespaces/utxo.ts, wallets/react/src/hub/autoConnect.ts, wallets/react/src/hub/lastConnectedWallets.ts, wallets/react/src/hub/useHubAdapter.ts
Added `canEagerConnect` action to namespaces so each namespace can be checked if is available for eager connect and also decouple `canEagerConnect` from `legacyProvider`. As a result, auto connect can now take place on a Phantom account which only supports evm addresses. 
This change can be tested by connecting to a phantom account containing only EVM address, then refreshing the page and observing that auto connect working properly.
=> feat: add can eager connect to namespaces

wallets/react/src/hub/lastConnectedWallets.ts
Wallets that do not support auto-connect are not stored in localStorage 
as part of the last connected wallets list. 
There was an error during disconnect, specifically when trying to filter 
the last connected wallets by the current wallet. Since there was no 
entry in localStorage for these wallets, the object was `undefined`, 
leading to a runtime error.
This PR makes the access to the last connected wallets optional, 
preventing the error when the value is missing.
=> fix: optional namespace removal to prevent error for wallets without autoconnect

widget/embedded/src/hooks/useStatefulConnect/useStatefulConnect.ts
Currently, when connecting to a wallet that has exactly one namespace, the app incorrectly triggers the namespace selection modal. This behavior is unintended, as wallets with a single namespace should bypass the modal and connect directly (or prompt for derivation path if required). This PR refactors the `handleConnect` function to align the wallet connection logic with the legacy implementation.
Tested by trying to connect to a wallet containing exactly one namespace.
=> feat: handle connecting wallet with exactly one namespace for hub

widget/embedded/src/components/BlockchainsSection/BlockchainsSection.tsx, widget/embedded/src/components/Layout/Layout.constants.ts, widget/embedded/src/components/Layout/Layout.tsx, widget/embedded/src/constants/configs.ts, widget/embedded/src/store/ui.ts
After deciding to make the widget height dynamic for mobile users based on their device viewport, we encountered an issue on the token selector page where the token list might appear too small, affecting the UX. To resolve this, I adjusted the number of blockchains in the blockchain section according to the page height changes.
Decrease your browser width below 640px, go to the token selector page, and adjust the browser height.
=> feat: adjust the number of blockchains in the token selector based on widget height changes

wallets/react/src/hub/lastConnectedWallets.ts, wallets/react/src/hub/useHubAdapter.ts, wallets/react/src/legacy/context.ts, wallets/react/src/legacy/types.ts, wallets/react/src/legacy/useLegacyProviders.ts, wallets/react/src/useProviders.ts
Added `connectNamespace`, `disconnectNamespace`, `getNamespaceState` to hub adapter and also some small changes to `lastConnectedWallets` to be able to add some namespaces to already existing namespaces for a provider in storage.
- https://github.com/rango-exchange/rango-client/pull/1093
- https://github.com/rango-exchange/rango-client/pull/1090
It can be tested after adding detached modal in another PR.
=> feat: add namespace connect and disconnect and get state

wallets/core/src/hub/namespaces/errors.ts, wallets/core/src/hub/namespaces/namespace.ts
Previously, failures in "before" action hooks were not handled properly, preventing "or" action hooks from executing. This caused the UTXO namespace to get stuck in a "connecting" state when connecting Phantom, especially if BTC was turned off in Phantom.
The issue stemmed from changeAccountSubscriber, a "before" hook for the "connect" action, which checked for instance. If the check failed, it threw an error, blocking the execution of "or" and "after" hooks.
This PR introduces the following fixes:
Wraps "before" hooks in a try/catch to ensure errors don't prevent "or" hooks from running.
Adds intoConnectionFinished to the "or" hooks for the "connect" action.
These changes ensure that the connection process proceeds correctly, even if a "before" hook encounters an error.
This change can …
=> fix: handle namespace before action failure

widget/embedded/src/components/HistoryGroupedList/HistoryGroupedList.tsx, widget/ui/src/components/SwapListItem/SwapListItem.tsx, widget/ui/src/components/SwapListItem/SwapListItem.types.ts, widget/ui/src/components/SwapListItem/SwapToken.tsx, widget/ui/src/components/SwapListItem/SwapToken.types.ts
If the source and destination blockchains in the current step are the same, the message "Waiting for swap transaction" will be displayed; otherwise, the message "Waiting for bridge transaction" will be shown.
=> fix: swap subtitle for history page

widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/utils/swap.ts
Updated the warning message related to step waiting for connecting wallet in swap details page from "Waiting for connecting wallet" to "Connect {walletName}".
You can test this by observing the warning message in swap details page for a step which is blocked for connecting the required wallet.
=> feat: add wallet name to waiting for connect wallet warning message

widget/embedded/src/components/Slippage/Slippage.tsx, widget/embedded/src/constants/swapSettings.ts, widget/embedded/src/store/slices/settings.ts, widget/embedded/src/utils/settings.ts
Four different ranges are defined for the slippage value:
**Error: x < 0.01**
- Show an error alert. This occurs only when the slippage value is 0.
**Standard: 0.01 ≤ x ≤ 5**
- No alerts. Acceptable range.
**High: 5 < x ≤ 30**
- Show a warning alert.
**Unacceptable: x > 30**
- Automatically set slippage to 30.
---------------------------------------------------------------------------------------------
- Limit the slippage input to a maximum of two decimal places.
- Ensure all visual feedback (error/warning alerts) is properly handled for both light and dark modes.
=> feat: add slippage validation on Settings page

widget/ui/src/containers/SwapInput/SwapInput.styles.ts, widget/ui/src/containers/SwapInput/SwapInput.tsx, widget/ui/src/containers/SwapInput/TokenSection.styles.ts, widget/ui/src/containers/SwapInput/TokenSection.tsx
Currently, on the homepage, token symbols with too many characters (such as some custom tokens) are not displayed properly, and in some cases, the alert for custom tokens may not appear. In this pull request, we've updated some styles to truncate long token symbols and ensure they are displayed correctly.
You could test with these sample tokens:
- 0x8d546c8e41d6c7a25855d0d9a6e0ef5d3b66808b
- 0xdb8f3858d6750f5772b9c77770807d29ec0395cb
=> fix: fix long token names in widget home page

widget/embedded/src/components/BlockchainsSection/BlockchainsSection.tsx, widget/embedded/src/components/CustomTokenModal/CustomTokenModal.styles.ts, widget/embedded/src/components/CustomTokenModal/CustomTokenModal.tsx, widget/embedded/src/components/Layout/Layout.constants.ts, widget/embedded/src/components/Layout/Layout.styles.ts, widget/embedded/src/components/Layout/Layout.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.Placeholder.tsx, widget/embedded/src/components/SwapDetails/SwapDetails.styles.ts, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/components/WalletStatefulConnect/DerivationPath.styles.ts, widget/embedded/src/components/WalletStatefulConnect/DerivationPath.tsx, widget/embedded/src/components/WalletStatefulConnect/Namespaces.styles.ts, widget/embedded/src/components/WalletStatefulConnect/Namespaces.tsx, widget/embedded/src/constants/configs.ts, widget/embedded/src/store/ui.ts, widget/ui/src/components/Modal/Modal.styles.ts, widget/ui/src/components/StepDetails/StepDetails.tsx
Some mobile users are having trouble seeing the call-to-action buttons at the bottom of certain pages. To resolve this, we plan to make the widget height dynamic on devices with a screen width of 768px or less. The widget will have a minimum height (matching its height on the home page when no token is selected) and a maximum height of 700px. The height will adjust based on the user's viewport size and the widget's offset from the top.
You can test these changes by decreasing the browser window width and adjusting the viewport height. Additionally, you can add elements above the widget in the app to check the effect of the offset on the widget's height.
=> feat: improve widget UX on small devices with dynamic height

wallets/core/src/hub/namespaces/namespace.test.ts, wallets/core/src/hub/namespaces/namespace.ts, wallets/core/src/namespaces/common/mod.ts, wallets/core/src/namespaces/common/or.ts, wallets/core/src/namespaces/evm/actions.ts, wallets/core/src/namespaces/solana/actions.ts, wallets/core/src/namespaces/sui/actions.ts, wallets/provider-phantom/src/namespaces/evm.ts, wallets/provider-phantom/src/namespaces/solana.ts, wallets/provider-phantom/src/namespaces/sui.ts, wallets/provider-phantom/src/namespaces/utxo.ts
Some wallet providers, such as Trust Wallet, do not throw errors using the standard `Error` object. This behavior can lead to issues when attempting to catch and rethrow these errors consistently.
This update refactors the `tryRunOrOperators` function to capture the responses returned by `or` actions. If a response is an instance of `Error`, it is rethrown directly. If not, it is wrapped in a new `Error` object. This approach ensures that all `or` actions consistently return proper `Error` instances.
To support this change, the only existing `or` action, `cleanAccountSubscribers`, has been updated accordingly.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …
=> fix: error rethrow in or cases

widget/ui/src/containers/SwapInput/TokenSection.styles.ts
A large gap appears between the token symbol and the warning alert when there are few characters; this spacing should be removed : 
Use max-width instead of width for the token symbol element.
Import custom tokens with symbols of varying lengths, including both short and long character counts:
29nZcMWKbq6kPr6icM9tLrYWQor2eACWr1ifrVU1pump
0xe95a392047c46359807e3fbb263492298bcd35f9
=> fix: adjust the warning alert position for custom tokens on the homepage

queue-manager/rango-preset/src/helpers.ts, queue-manager/rango-preset/src/hooks.ts, queue-manager/rango-preset/src/index.ts, queue-manager/rango-preset/src/types.ts, wallets/shared/src/helpers.ts, widget/embedded/src/containers/Wallets/Wallets.tsx, widget/embedded/src/containers/Wallets/Wallets.types.ts, widget/embedded/src/containers/Wallets/useUpdates.ts, widget/embedded/src/hooks/useBootstrap/useBootstrap.ts
There was a problem in retrying on swaps when a wallet related to a swap gets connected. The problem mostly was happening on Solana transactions. 
In this PR, tried to improve the model for storing lastConnectedWallet and also changed the `retryOn` function to execute even if `network` of `lastConnectedWallet` is `null` (happens on Solana wallets).
Also, I've added a "disconnectAll" button in "ConfirmSwapPage" in the second commit to help testing the retry functionality. This change should be reverted.
Fixes # 2134
Tested by disconnecting wallet before confirming the transaction and observing
=> fix: fix retry swap on connect wallet

widget/ui/src/components/StepDetails/StepDetails.tsx
Fixes a labeling issue in the routing section for cross-chain transactions. The term **"Bridge"** is now correctly displayed when `fromChain !== toChain`.
- Added a condition to check if `fromChain !== toChain`.
- If true, the label now shows **"Bridge"** instead of **"Swap"**, following the same logic as in:
[SwapToken.tsx#L113](https://github.com/rango-exchange/rango-client/blob/4bd8209c3eb4cd11c163ba7ccc41259475a336fd/widget/ui/src/components/SwapListItem/SwapToken.tsx#L113)
=> fix: show correct terms in routing section of cross-chain transactions

wallets/core/src/builders/namespace.ts, wallets/core/src/hub/namespaces/namespace.test.ts, wallets/core/src/hub/namespaces/namespace.ts, wallets/core/tests/providers.test.ts, wallets/react/src/hub/useHubAdapter.ts
**Summary:**  
This PR introduces a `has` method to the namespace proxy, allowing us to check for the existence of a property. It also resolves the issue where hub wallets without `canEagerConnect` were incorrectly added to `last-connected-wallets`.
**Changes:**
- Added a `has` method to the namespace proxy:
- Returns `true` if the requested property:
- Is one of the allowed methods,
- Has a value of type `number` or `string`, or
- Corresponds to an existing action on the namespace.
- Added a `hasAction` method to the `Namespace` class to support this logic.
- Updated `hubAdapter` to use `'canEagerConnect' in namespace` instead of directly checking the value:
- This ensures the `has` method on the proxy is invoked.
- Prevents hub wallets without `canEagerConnect` from being added to …
=> Add `has` Method to Namespace Proxy and Fix Hub Wallet `canEagerConnect` Check

widget/embedded/src/constants/errors.ts, widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.helpers.ts, widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.ts, widget/embedded/src/types/quote.ts
Show the error message returned in the response instead of using the default one
1. Connect to the Phantom wallet.
2. Make a swap on the Sui blockchain.
3. At the wallet selection step, add a custom Sui destination and then click Confirm.
=> fix: display error message from response instead of default fallback

.husky/post-merge, .husky/pre-merge-commit
The pre-merge-commit and post-merge hooks modify commit hashes after pulling any branch from the origin, which causes divergence when attempting to push the updated branch back to origin. For now, we've removed these hooks to resolve the issue and will work on finding a proper way to reintroduce them without causing divergence.
=> chore: remove pre-merge-commit and post-merge hooks

widget/embedded/src/components/NoResult/NoResult.tsx, widget/embedded/src/components/NoResult/NoResult.types.ts, widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.helpers.ts, widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.styles.ts, widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.tsx, widget/embedded/src/components/QuoteWarningsAndErrors/QuoteWarningsAndErrors.types.ts, widget/embedded/src/components/QuoteWarningsAndErrors/SlippageWariningModal.tsx, widget/embedded/src/components/Slippage/Slippage.styles.ts, widget/embedded/src/components/Slippage/Slippage.tsx, widget/embedded/src/components/SlippageWarningsAndErrors/SlippageWarningsAndErrors.helpers.ts, widget/embedded/src/components/SlippageWarningsAndErrors/SlippageWarningsAndErrors.tsx, widget/embedded/src/components/SlippageWarningsAndErrors/SlippageWarningsAndErrors.types.ts, widget/embedded/src/components/SwapMetrics/SwapMetrics.constants.ts, widget/embedded/src/components/SwapMetrics/SwapMetrics.helpers.ts, widget/embedded/src/components/SwapMetrics/SwapMetrics.styles.ts, widget/embedded/src/components/SwapMetrics/SwapMetrics.tsx, widget/embedded/src/components/SwapMetrics/SwapMetrics.types.ts, widget/embedded/src/components/SwapMetrics/index.ts, widget/embedded/src/hooks/useSwapInput.ts, widget/embedded/src/pages/ConfirmSwapPage.tsx, widget/embedded/src/pages/Home.tsx, widget/embedded/src/store/app.ts, widget/embedded/src/store/slices/settings.ts, widget/embedded/src/utils/settings.ts
In this PR, the display of slippage-related warnings and errors on the swap page has been improved. The "Recommended Slippage" warning has also been removed from the swap confirmation page.
Additionally, a new row has been introduced to show both the slippage value (highlighted with appropriate warning or error styles) and the swap rate, which represents the conversion rate from the destination token to the source token.
Users can toggle the direction of the rate (i.e., switch between source and destination tokens), and their selected preference will persist unless manually changed.
=> feat: show slippage and rate in swap box

widget/charts/src/components/BarChart/BarChart.constants.ts, widget/charts/src/components/BarChart/BarChart.helpers.ts, widget/charts/src/components/BarChart/BarChart.tsx, widget/charts/src/components/BarChart/BarChart.types.ts
We are working on setting Custom Period range by server, if data is more than 90, the label shown messy.
Fixes RF-2431
You should link the `charts` in `explorer`.
=> fix: if data exceed 90 days, bottom axis should be shown correctly

wallets/core/src/hub/hub.ts, wallets/core/src/hub/provider/provider.test.ts, wallets/core/src/hub/provider/provider.ts, wallets/core/src/hub/store/providers.ts, wallets/core/src/hub/store/selectors.ts, wallets/core/src/hub/store/store.test.ts, wallets/core/tests/hub.test.ts, wallets/react/src/hub/useHubRefs.ts, wallets/react/src/hub/utils.ts
Previously, in the `getHub` method, we checked if:
- the hub does not exist, **or**
- there is no hub provider,  
to decide whether to create a new hub.
However, there was a **third condition**: if the requested providers from the config did not match the available providers on the hub, we would also recreate the hub.
After investigating, we found the reason for this: sometimes, in the playground, the filter was changed, and the requested provider was not available on the hub anymore. Recreating the hub prevented errors indicating that a requested provider didn’t exist.  
**However, this approach reset the state of providers.**
In our first attempt to fix this, we tried re-initiating the providers:  
[Previous PR #1101](https://github.com/rango-exchange/rango-client/pull/1101)
But with …
=> fix: avoid hub recreation

wallets/react/src/hub/useHubAdapter.ts, wallets/react/src/hub/utils.ts
There was a problem in the process of connecting EVM namespace on hub wallets. The root cause was that the event for connecting to the EVM namespace was being propagated with an incorrect payload, specifically, an empty `supportedBlockchains` field in `eventInfo` which led to an incorrect wallet state in the "Confirm Wallets" modal. The issue was originated by that the `api` object passed to `mapHubEventsToLegacy` function, which was being used to get the supported chains for wallets, was stale which was resulting in an empty list for `supportedBlockchains` when calling `getWalletInfo`. In this PR, the issue is fixed by passing a fresh reference to meta.allBlockchains into mapHubEventsToLegacy, ensuring supported chains are processed correctly.
Tested by connecting EVM namespace on …
=> fix: fix incorrect state after connecting evm namespace on hub wallets

widget/embedded/src/store/slices/wallets.ts
Added a flag to `getConnectedWalletsDetails` result to indicate that the token related to the `balanceItem` is supported or not by checking if it is included in meta.
=> chore: add isSupported flag to getConnectedWalletsDetails result

wallets/provider-slush/src/legacy/index.ts
Clicking on wallets in the Playground caused a crash. This was due to a bug in `getWalletInfo` that's being addressed in **PR #1167**. The specific issue here was that `getWalletInfo` for **Slush Wallet** in its *legacy model* was also throwing an error, meaning our fallback mechanism wasn't working.
I've added a basic `getWalletInfo` implementation to the **legacy version of Slush Wallet**. This is a **temporary fix** to prevent the crash and unblock our current release. 
=> fix: wallets playground crash on hub provider info access (temporary fix)

widget/embedded/src/pages/HistoryPage.tsx
This PR addresses an issue where the search input on the History page retained its last value upon re-entry, even after navigating away without explicitly clearing it.
This PR resolves the issue by disabling autocomplete for the search input field on the History page.
=> fix: turn autocomplete off for history search input

widget/playground/src/constants/urls.ts
In Playground, the Rango website link currently points to the widget instead of the landing page. It should redirect to the landing page.
=> fix: update Rango website link to point to landing page instead of widget

widget/embedded/src/utils/validation.test.ts
The precision option of `faker.number.float` [will be deprecated](https://fakerjs.dev/api/number.html#float) in the next major version. This PR changes it to `multipleOf` instead, hence removing the warnings from the [CI logs](https://github.com/rango-exchange/rango-client/actions/runs/15557618986/job/43802006925#step:7:41):
```python
[@faker-js/faker]: faker.number.float({ precision }) is deprecated since v8.4 and will be removed in v9.0. Please use faker.number.float({ multipleOf }) instead.
```
Run the test suite.
=> fix: change `faker.number.float` precision option to `multipleOf`

wallets/provider-trustwallet/package.json, wallets/provider-trustwallet/src/legacy/signer.ts, wallets/provider-trustwallet/src/legacy/signers/solanaSigner.ts
Currently, attempting to sign a message using Solana account on Trust Wallet results in an error indicating that the `request` method is not available on the provider. This PR introduces a custom message signing implementation specifically for Solana transactions when using the Trust Wallet provider, effectively bypassing the error and ensuring compatibility.
Tested by signing a message using Solana account on trust wallet in the profile page of Rango app.
=> fix: fix trust wallet provider sign message error

wallets/core/src/namespaces/evm/actions.ts
Trust Wallet's in-app browser doesn't provide a `removeListener` function on its injected instance, which caused disconnect functionality to fail. The code was attempting to remove listeners in the `after` hook, and when this threw an error, the disconnect process would halt and not continue to other namespaces.
This PR makes the `removeListener` calls optional to handle cases where the function is unavailable, ensuring the disconnect process continues across all namespaces even in Trust Wallet's environment while maintaining backward compatibility with other wallet providers.
=> fix: trust wallet disconnect problem in its in-app browser

wallets/core/src/namespaces/evm/actions.ts
This PR addresses an issue with Trust Wallet's in-app browser, which returns the `chainId` as a number instead of a hexadecimal string. This was causing an error in the `accountId.format` function, which expects the `chainId` in hex format.
To fix this, I've added a conditional check to convert `chainId` to a hex string when it's returned as a number. This ensures compatibility with Trust Wallet without affecting other providers.
* Normalize `chainId` to hex string if it’s returned as a number.
=> fix: convert trust-wallet in-app browser chainId to hex string

wallets/core/src/hub/mod.ts, wallets/core/src/mod.ts, wallets/core/src/namespaces/evm/utils.ts, wallets/provider-trustwallet/src/namespaces/evm.ts, wallets/provider-trustwallet/src/namespaces/solana.ts, wallets/provider-trustwallet/src/utils.ts, wallets/react/src/hub/helpers.ts, wallets/react/src/hub/useHubAdapter.ts
Currently, if user select multiple namespace to connect to and rejects the connect request in wallet for one namespace, widget will try to connect to other remaining namespaces resulting in multiple connect requests on wallet which can be annoying for the user. In this PR, this behavior is changed by checking for the code of error related to failed connect request and if it is equal to 4001 (which is documented [here](https://eips.ethereum.org/EIPS/eip-1193#provider-errors) for Ethereum wallets and also is accepted by [Solana wallets](https://docs.phantom.com/solana/errors)) the connection for remaining namespaces will be aborted.
Fixes # 2399
Tested by trying to connect to all namespaces on Phantom and Trust wallet and rejecting the connect request in wallet and observing that remaining …
=> fix: abort all namespace connections if user rejects one connect request

widget/embedded/src/components/Slippage/Slippage.styles.ts, widget/embedded/src/components/Slippage/Slippage.tsx, widget/ui/src/components/TextField/TextField.styles.ts, widget/ui/src/components/TextField/TextField.tsx, widget/ui/src/components/TextField/TextField.types.tsx
Add support for a status prop in the text field that changes the border color based on the validation state (default, error, warning, success).
=> feat: add status to textField

wallets/core/src/legacy/types.ts, wallets/core/src/legacy/wallet.ts, wallets/provider-ledger/src/helpers.ts, wallets/provider-trezor/src/helpers.ts, wallets/react/src/legacy/types.ts, wallets/shared/src/rango.ts, widget/embedded/src/containers/Wallets/useUpdates.ts, widget/embedded/src/store/slices/wallets.ts, widget/embedded/src/types/wallets.ts, widget/embedded/src/utils/swap.ts
In HD wallets, a derivation path specifies the location of keys and addresses. We rely on this path for Ledger and Trezor wallets, particularly during connection and transaction signing. As part of redesigning the 1SwapDetailsModal1 and improving the wallet connection flow—which is required to proceed with a transaction—we now need to persist the derivation path within the swap object. This ensures that if a wallet is disconnected, we can reconnect using the same derivation path.
Also you can see the usage of this in the related PR (in this file: `widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.ConnectWallet.tsx`).
- Added `derivationPath` to `ProviderConnectResult` type
- Added `derivationPath` to the return object of `connect` method for Ledger and Trezor wallets
- …
=> feat: add derivation path to swap wallets

queue-manager/rango-preset/src/actions/checkStatus.ts, queue-manager/rango-preset/src/actions/createTransaction.ts, queue-manager/rango-preset/src/helpers.ts, queue-manager/rango-preset/src/services/eventEmitter.ts, widget/embedded/src/components/Quote/Quote.tsx, widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.helpers.ts, widget/embedded/src/hooks/useConfirmSwap/useConfirmSwap.ts, widget/embedded/src/hooks/useSwapInput.ts, widget/embedded/src/types/quote.ts, widget/embedded/src/utils/swap.ts
We aim to gather all errors that users encounter during the swap flow. This includes:
- `quoteError`
- `confirmSwapError`
- `createTransactionError`
- `checkTransactionStatusError`
- `checkApprovalStatusError`
Each error will be logged along with relevant contextual data that can help us debug the issue. In the production environment, these logs will be forwarded to Sentry for centralized monitoring and analysis.
For testing, you can try reproducing the errors and check the console output in the development environment.
=> refactor: enhance swap error handling and gather data for debugging

queue-manager/rango-preset/src/shared.ts
According to that blockchain is not available in transfer transaction, it was resulting in that required wallet for the transfer transaction step not getting found and failing to find the correct wallet and signing transactions. It is fixed in this PR by checking for the source wallet address among the list of wallets in the swap.
Tested by signing transfer transactions using Phantom wallet.
=> fix: fix undefined wallet type for transfer transactions

queue-manager/rango-preset/src/actions/executeTransaction.ts, queue-manager/rango-preset/src/helpers.ts, wallets/shared/src/helpers.ts, widget/embedded/src/components/SwapDetails/SwapDetails.tsx, widget/embedded/src/components/SwapDetailsAlerts/SwapDetailsAlerts.Warning.tsx, widget/embedded/src/components/SwapDetailsAlerts/SwapDetailsAlerts.tsx, widget/embedded/src/components/SwapDetailsAlerts/SwapDetailsAlerts.types.ts, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.NetworkState.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.tsx, widget/embedded/src/components/SwapDetailsModal/SwapDetailsModal.types.ts, widget/embedded/src/utils/swap.ts
Improved switch network modal in swap details page adding success and error states so if the switch network process fail for any reason, a modal containing the appropriate message will be displayed with "try again" option and if the switch network process success,  a success modal will be displayed.
- Removed `resetNetworkStatus` in `actions/executeTransaction` so switch network stay open after successfully switching network
- Added calling `updateNetworkStatus` with appropriate params to display switch network failed modal on switch network failure
- Improved changing and maintaining the state of swap details modal
- Applied required ui changes to switch network modal in swap details page.
Related PR: https://github.com/rango-exchange/rango-types/pull/50
Tested by running a transaction …
=> feat: improve swap details page switch network modal

widget/embedded/src/components/SearchInput/SearchInput.tsx, widget/ui/src/components/TextField/TextField.styles.ts, widget/ui/src/components/TextField/TextField.tsx
The input was wrapped in a div with padding, which caused the clickable area to be misaligned or broken. This PR refactors the layout to preserve the padding effect without interfering with the input's usability.
=> fix: ensure input remains fully clickable by adjusting wrapper padding

widget/embedded/src/components/CustomDestination/CustomDestination.styles.ts, widget/embedded/src/components/SearchInput/SearchInput.styles.ts, widget/embedded/src/components/SearchInput/SearchInput.tsx, widget/embedded/src/components/Slippage/Slippage.styles.ts, widget/embedded/src/pages/AddCustomTokenPage.tsx, widget/playground/src/components/SearchInput/SearchInput.styles.ts, widget/playground/src/containers/FunctionalLayout/FunctionalLayout.styles.ts, widget/ui/src/containers/SwapInput/SwapInput.styles.ts
Some input fields in the UI have extra padding, while others have less padding compared to the production version, causing inconsistencies in spacing and alignment.
=> fix: adjust all input paddings

widget/embedded/src/pages/HistoryPage.tsx
Fixed translating swap tab items in history page.
=> fix: fix translating swap tabs in history page

queue-manager/rango-preset/src/actions/executeTransaction.ts, wallets/core/store/package.json, wallets/react/src/hub/useHubAdapter.ts, wallets/react/src/hub/utils.ts, widget/embedded/src/components/StatefulConnectModal/StatefulConnectModal.tsx, widget/embedded/src/components/WalletStatefulConnect/Detached.tsx, widget/embedded/src/components/WalletStatefulConnect/Detached.types.ts, widget/embedded/src/components/WalletStatefulConnect/NamespaceDetachedItem.tsx, widget/embedded/src/components/WalletStatefulConnect/Namespaces.styles.ts, widget/embedded/src/components/WalletStatefulConnect/Namespaces.tsx, widget/embedded/src/components/WalletStatefulConnect/Namespaces.types.tsx, widget/embedded/src/hooks/useStatefulConnect/useStatefulConnect.state.ts, widget/embedded/src/hooks/useStatefulConnect/useStatefulConnect.ts, widget/embedded/src/hooks/useStatefulConnect/useStatefulConnect.types.ts, widget/embedded/src/pages/WalletsPage.tsx, widget/embedded/src/utils/wallets.ts
Added single selection to detached modal.
- State for wallet item in wallets page will be displayed as "Connected" instead of "Partially connected" when a wallet is partially connected and defined as single selection wallet
- Detached modal will be displayed for hub wallets after confirming derivation path modal
- If derivation path is needed for connecting a namespace, trying to connect to the namespace in detached modal will result in navigating to derivation path modal
- If wallet is defined as single selection wallet, trying to connect to a namespace in detached modal will result in disconnecting on other namespaces
- derivation path is added to hub wallet events
Fixes # 2239
Tested by connecting and disconnecting on different namespaces of ledger wallet in detached modal.
=> feat: add single selection to detached modal

widget/embedded/src/components/WalletStatefulConnect/DerivationPath.tsx, widget/ui/src/components/MessageBox/DefaultMessageBox.tsx
Added `className` to derivation path modal elements to enable styling them from outside of the widget.
=> chore: add classname to derivation path modal elements

widget/embedded/src/components/WalletStatefulConnect/Detached.tsx, widget/embedded/src/components/WalletStatefulConnect/Detached.types.ts
Added optional `confirmText` prop to `Detached` component enabling customizing the text of confirm button.
=> feat: make detached confirm text customizable

wallets/core/src/namespaces/common/mod.ts, wallets/core/src/namespaces/solana/actions.ts, wallets/core/src/namespaces/solana/mod.ts, wallets/provider-metamask/package.json, wallets/provider-metamask/readme.md, wallets/provider-metamask/src/actions/solana.ts, wallets/provider-metamask/src/builders/solana.ts, wallets/provider-metamask/src/constants.ts, wallets/provider-metamask/src/legacy/index.ts, wallets/provider-metamask/src/namespaces/evm.ts, wallets/provider-metamask/src/namespaces/solana.ts, wallets/provider-metamask/src/provider.ts, wallets/provider-metamask/src/signer.ts, wallets/provider-metamask/src/signers/solana.ts, wallets/provider-metamask/src/types.ts, wallets/provider-metamask/src/utils.ts, wallets/readme.md, yarn.lock
This PR adds Solana support to the MetaMask Provider by implementing the Wallet Standard. The core challenge was a mismatch between the method signatures and behavior of our previous default injected provider instance and the new Wallet Standard-based instance.
To unblock this high-priority integration, the initial implementation includes:
1.  A custom `SolanaSigner` class, as the signer methods (e.g., `signMessage`, `signTransaction`) on the Wallet Standard instance are different from those on our legacy injected provider.
2.  A temporary set of custom actions to handle Solana-specific operations through the new Wallet Standard interface.
This is a stopgap solution. The long-term plan is to deprecate this custom code once Wallet Standard support is fully integrated and standardized into …
=> feat: add solana support to metamask
